---
title: "See the bottom of the file for title"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "A simple example of survival data"
  topic_02: "Overall Kaplan-Meier curve"
  topic_03: "The log rank test"
  topic_04: "The hazard function"
  topic_05: "The Cox regression model"
  topic_06: "Assumptions and data management"
editor: source
---

## Topics to be covered

```{r}
# Preliminaries, if needed

# Keep this chunk, even if no code, so that
# params is populated from the yaml header.

# To print speaker notes, add
#   ?print-pdf&showNotes=separate-page 
#   to the end of the URL. Then open the
#   print dialog box (ctrl-P) and choose
#   Save as PDF for the printer. Other 
#   options, like Microsoft Print to PDF
#   do not seem to work.
```

-   What you will learn
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`

{{< include _b2-08-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

{{< include _b2-08-02.qmd >}}

## Live demo, `r params$topic_02`

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`
    
{{< include _b2-08-03.qmd >}}

## Live demo, `r params$topic_03`

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`
    
{{< include _b2-08-04.qmd >}}

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`

{{< include _b2-08-05.qmd >}}

## Live demo, `r params$topic_05`

## Break #5

-   What you have learned
    -   `r params$topic_05`
-   What's coming next
    -   `r params$topic_06`

{{< include _b2-08-06.qmd >}}

## Summary

-   What you have learned
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`

## Additional topics??

::: notes
-   Kaplan-Meyer - Survival Analysis
    -   Define Survival Analysis
    -   List the scientific applications of Survival Analysis
    -   Know the general overview of Survival Analysis
    -   Identify the type of data used in Survival Analysis
    -   Identify data requirements for Survival Analysis
    -   Identify the research design for a Survival Analysis
    -   List the benefits of Survival Analysis
    -   Define "censoring"
    -   Define "event observation"
    -   Outline the history of Survival Analysis
    -   Define "Life Tables"
    -   List the characteristics of Kaplan-Meier Survival Analysis
    -   List and define the assumptions of The Kaplan-Meier method
    -   Explain how to test Assumption #6 - Censorship equality
    -   Define "left censoring"
    -   Define "right censoring"
    -   Define the 2 goals of the Kaplan-Meier method
    -   Define the characteristic of the Event Status variable
    -   Define the characteristic of the Time variable
    -   Define the Subject Identifier variable
    -   Define the Between Subjects Factor
    -   Run a Kaplan-Meier analysis using SPSS
    -   Define and explain the Log-Rank Test, the Breslow test and the Tarone-Ware test.
    -   Interpret a Survival Functions Plot
    -   Identify the median survival values on a Survival Functions Plot
    -   Interpret the median values of a Kaplan-Meier Survival analysis
    -   Identify the useful functions of a survival distribution
    -   Explain the pair wise comparisons generated in a Kaplan-Meier survival analysis
    -   Create a complete write-up of a Kaplan-Meier survival analysis
-   Cox Regression
    -   Define Cox Regression
    -   Explain what a Cox Regression analysis is used for
    -   Compare and contrast a Cox Regression analysis and a Kaplan-Meier survival analysis
    -   Identify the benefits of a Cox Regression analysis
    -   Define Hazard Function
    -   Explain the Cox Regression Equation
    -   Define "maximum Likelihood"
    -   Interpret a positive regression coefficient and a negative regression coefficient
    -   Compare and contrast the interpretation of a  Cox Regression analysis and a Kaplan-Meier survival analysis
    -   Identify the assumptions of a Cox Regression analysis
    -   Define the Proportional Hazards assumption
    -   Explain how to test the Proportional Hazards assumption
    -   Explain what will occur if the Proportional Hazards assumption is violated
    -   Run a Cox Regression analysis in SPSS
    -   Interpret the Omnibus Tests of Model Coefficients
    -   Interpret the Beta coefficients of a Cox Regression analysis
    -   Interpret the Hazard Function Curve
    -   Create a complete write-up of a Cox Regression analysis
-   Learning objectives
    -   Define Propensity Score
    -   Define propensity Score Matching
    -   Explain the main reason for the use of propensity scores
    -   Explain the use of Propensity Scores for a Treatment-Control Study
    -   List the 3 relationship between the covariate, the Outcome Variable and the Treatment assignment
    -   Define the 3 relationship between the covariate, the Outcome Variable and the Treatment assignment
    -   State the "biggest" challenge of Propensity Score calculation
    -   Define the most important step in Propensity Score calculation
    -   Explain the mathematical theory of the Propensity Score
    -   List and define the Assumptions for Propensity Score calculation
    -   Explain the problem of a Propensity Score of 0 or 1
    -   Explain the Area of Common Support
    -   Explain the need for an ideal  number of covariates for the Propensity Score calculation
    -   Explain the selection of covariates for Propensity Score Calculation
    -   List and explain the methods for matching groups using Propensity Scores
    -   List and explain the limitations/concerns of using Propensity Scores
    -   Explain the benefits of Propensity Score Matching over using a regression model for covariate control.
    -   Explain the benefits of using a regression model over Propensity Score Matching for covariate control.
:::

<!---
      You have to put the title down 
      here to override the titles of
      all the include files.
--->

---
title: "Comments for MEDB 5502, Module 08, survival analysis"
---