---
title: "Three dichotomies of measurement"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Break #4

-   What you've seen so far
    -   Five case studies
-   What is coming next
    -   Three dichotomies of measurement

::: notes

So far, you've seen five case studies where you may want to assess reliability and validity. These are very different types of measurements and you can classify them into three important dichotomies. These three dichotomies will help you assess the best approach to take for assessing reliability and validity.

:::

## First dichotomy: Who is the measurer?

-   Self reported outcomes
    -   Also know as patient reported outcomes
-   Researcher evaluations
    -   Only when concerned about subjectivity

::: notes

I think it is a bit unfair, but there is a lot of distrust of self reported outcomes among researchers. Why not believe what the patient says about himself or herself? Part of it might be that a patient's answers could potentially be influenced by their mood. They might also be influenced by a desire to look good. They may want to give an answer that they think the interviewer wants to hear.

There is also a belief that  reported outcome measures vary too much from one individual to another. Some people are stoic to a fault and others will complain endlessly at the drop of a hat.

It is worth noting that these factors also influence researcher observation, but researchers don't like it when you point this out to them. It's mostly a good thing that researchers require a high level of scrutiny of  reported outcomes, but perhaps other measures deserve just as high a level of scrutiny.

:::

## Second dichotomy: How many pieces?

-   Composite scores
    -   Sum or average
-   Single measurement

::: notes

Many measures in research are composites of one or more items. These individual items are scored and added up to get a total. Sometimes you average them instead of summing them. That's a minor distinction. In general, a composite measure involves evaluating something from many different angles. If you do this well,, this can be a very effective approach. But you do need to be careful.

In contrast, some measures are just a single number and there is no summing or averaging involved. There is just a single question or a single evaluation. It is a difficult decision to choose whether to develop a measurement using a composite scale versus a single measurement, and it depends a lot on what you are measuring.

The general consensus among researchers is that you get a better picture of something with a composite scale, but some measures do not warrant this extra effort.

:::

## Third dichotomy: is the measure soft or hard?
-   Psychological or social constructs
    -   Created and accepted by you and me
    -   Impossible to observe directly
    -   Examples: stress, anxiety
  
::: notes

Constructs are measurements of something that is considered soft. They do not have an indepent existence but are created by society. Almost all measures in psychology, such stress and anxiety, are constructs because you do not have the ability to peer inside someone's brain.

There is a gray area, of course. We can indeed peek inside the brain to some extent with new imaging equipment, but I would argue that even these measures are not direct measures.

:::
  
## Third dichotomy: is the measure hard or soft
-   Biological or physical measure
    -   Has an objective reality
    -   Potential for direct observation
    -   Example: obesity, dementia
  
::: notes

Some people argue that everything is socially constructed, but this is rather silly, in my opinion. Some things have an objective reality and were not created by us. Obesity is a physical concept that can be measured using body mass index, percentage of body fat, waist to hip ratio and many others. They all represent a physical manifestation of excess weight. Dementia also has a physical manifestion. You can't measure it without autopsy perhaps, but there is a physical change in your brain that causes dementia.

:::

