---
title: "Clinical Research Methods, Week 9"
author: "Steve Simon"
output:
  html_document: default
---

```{r echo=FALSE}
source(file="prelims.R", echo=FALSE)
```

Created: Tuesday, March 19, 2019

Updated: `r format(Sys.Date(), "%A, %B %d, %Y")`

Please complete all work by midnight, `r mon[11]` to receive full credit.

## Week 9: Reliability and validity

### Learning objectives for this week

* To discuss the importance of measurement reliability and describe methods of assessing it

* To discuss the importance of measurement validity and to describe methods of assessing it

### Reading for this week

`r read_text("copyright")`

#### Required reading

* Gliner, Morgan, and Leech, Chapters 11, 12

#### Recommended reading

* Deshpande PR, Rajan S, Sudeepthi BL, Abdul Nazir CP. Patient-reported outcomes: A new era in clinical research. Perspect Clin Res. 2011;2(4):137-44. Available in [html format](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3227331/).

* McKenna SP. Measuring patient-reported outcomes: moving beyond misplaced common sense to hard science. BMC Med. 2011;9:86. Published 2011 Jul 14. doi:10.1186/1741-7015-9-86. Available in [html format](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3170214/) or [PDF format](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3170214/pdf/1741-7015-9-86.pdf).

* U.S. Food and Drug Administration. Patient-Reported Outcome Measures: Use in Medical Product Development to Support Labeling Claims (final). Available in [PDF format](https://www.fda.gov/Drugs/GuidanceComplianceRegulatoryInformation/Guidances/UCM193282).

* Changing Minds. Types of Reliability. Available in [html format](http://changingminds.org/explanations/research/design/types_reliability.htm).

* Paul C. Price, Rajiv Jhangiani, & I-Chant A. Chiang. Understanding Psychological Measurement. Chapter 5 in an open source textbook, Research Methods in Psychology. Available in [html format](https://opentextbc.ca/researchmethods/chapter/understanding-psychological-measurement/).

* Padilla JL, Benítez I. Validity evidence based on response processes. Psicothema. 2014;26(1):136-44. doi: 10.7334/psicothema2013.259. Available in [PDF format](http://www.psicothema.com/pmidlookup.asp?pmid=24444741).

### Assignments for this week

* Q09. Complete the quiz on the canvas website.

* (Not for credit). Start thinking about a methods section for your research question. In particular, what variables to you plan to collect? Which one(s) would warrant reliability or validity assessments? What information can you glean from the literature on reliability and validity. Note: it is okay to do research on "hard" measurements that do not require extensive reliability or validity checks. Also, review the material from the previous week and use it to describe the type of sample you will be using.

### Discussion questions for this week

* D09-01. `r read_text("minute-paper")`

* D09-02. (Two points) Find a paper that provides an extensive study of the validity and/or reliability of a measurement. Hint: do a PubMed search, but restrict yourself to articles where the words "validity" or "reliability" appear in the title. Provide a three or four sentence summary. List the types of reliability and/or validity that the paper uses. Include a link, if the article is available openly, or attach a copy if it is not openly available. 

* D09-EC. `r read_text("extra-credit")`
