---
title: "Identify a research problem"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Identify a research problem

-   Definitions are vague
    -   What is a problem? question? aim? goal?
    -   Sources of research problems
        -   Read
        -   Listen
        -   Observe

::: notes
There are varying terms: research problem, research question, research aim, research goal, that all involve stating in very general terms what you can do.

These represent statements about issue the you are trying to address, or what are you trying to discover.

I find these distinctions annoying, and prefer to talk only about a research hypothesis. We'll get to that in a bit.

You can find your research problem during your literature review. You can look at replicating someone else's work or extending it into a new area.

Pure replications are rare because of resource limitations, but there is a lot of research showing that many important research findings are not replicable.

You may also get good research ideas from attending other research presentations, such as thesis defenses of your fellow students or at regional/national research conference. Good stuff, good stuff.

You may hear about topics in the classes that you take. I, for example, am doing some interesting work on patient accrual models using a Bayesian approach. Ask me anytime, and I'll tell you more about it than you really want to hear.

If you are already working, what comes up in that environment? Watch what is going on and think about ways that you might improve things.

I want to put in a big plug for community-based participatory research. This is another way to develop research ideas. You ask people who are affected by the research you are thinking about doing what they think would work. It forces you to distill your ideas and explain them at a lay person's level and I think that it is good. It also requires great listening skills and an open mind. The people who you want to do research on have quite a different feeling.
:::

## Characteristics of a good research problem

-   More dichotomies
    -   Broad vs Narrow
    -   Widespread vs Limited interest
    -   Well-researched vs Unknown territory

::: notes
A good research problem. How broad versus narrow? Narrow enough to be feasible, but broad enough to be of interest to a large audience. I need to warn you here. I have helped a lot of students over the years with their thesis or dissertation work, and when I ask them afterwards what they would have changed, the most frequent comment was "I wish I had collected less data." They really didn't take advantage of all the data they collected. They put 60 questions on a questionnaire, for example, but did a serious analysis on only 5 of those questions.

You should think of your thesis or dissertation not as a single shot, but the first shot in a series of volleys. If your research yields more questions to be answered, that's actually a good thing. Let's be honest. You're not going to answer every question or solve every problem with just one study.

Should you work in an area where there is wide-spread interest. That's good in some ways, but you need to make sure that you are very current with what is being done (or that you are being advised by someone who knows what is currently being done). Otherwise, you run the risk of having new research published while you're halfway through your study that make your study obsolete. Attending research conferences is great if you want to know what the current work is in an area with broad interest.

There's less risk if you're working in an area that is not "hot." I also think it is advisable to do things that other people are not doing. This is what I do in my career, rather than doing something that someone else could easily do as well as you could. Work in a neglected area has a lot of value, but always beware. Is a neglected field being neglected because it is an area that is unlikely to bear any fruit?

So is Working in a neglected area a good thing? I can't answer that question. It all comes down to the question: do you want to be a big fish in a small pond or a small fish in a big pond?

Closely related is whether you want to be a pioneer and the first to embark in a new area, or do you want to add to a problem that has already been researched.

A third choice that faces you is whether you study a well-researched area or if you venture into "unknown territory". Do you want to be a pioneer, for example? 

If you want to be a pioneer, think about small scale "proof of concept" studies. These study a narrowly defined population and may not be set in a very realistic field setting. If you want to work in a well-researched area, consider a pragmatic study, one that studies and broad base of patients with few artificial restrictions. It uses a setting that very closely approximates how health care is actually delivered in the real world.  Also make sure, if there is still a gap that needs to be filled. Stay away from a research area that is so well researched that there are no important problems left to solve.
:::

## Considerations in Choosing a Topic, 1 of 2

-   Resources
    -   Time
    -   Cost
    -   Support
    -   Access
    -   Control

::: notes
Timing is especially important in this program. Prospective studies and especially prospective longitudinal studies take more time than you may have available.  We've had some students who have done a prospective study but most of them to retrospective students. 

Randomized studies, because they have to put much more machinery in place than observational studies, are more expensive than observational studies. 

Resources go beyond the financial. Do you have the right expertise or do you have access to colleagues who have that expertise. The era of the "Lone Ranger" scientist is long gone.

Also make sure you have access to the patients that you need for your research. for most studies, your access to patients depends on other people. 

Are you in a position of sufficient authority to get the research done, or do you have someone on your team who has that authority? You can't just walk into a clinic and start ordering people around.

What resources you have at your disposal will identify that scope of the problem that you are able to tackle. Don't bite off more than you can chew, as the saying goes. Don't try to solve every problem all at once. Bite size pieces is what it important here.

Contribution to the profession addresses the "so what" question. Is it going to be publishable. You shouldn't be obsessed about publication, but it is a marker of whether the problem is considered important to others besides yourself.
:::

## Considerations in Choosing a Topic, 2 of 2

-   Interest and enthusiasm
-   Scope of the problem
-   Contribution to the profession
    -   Adapted from Cottrell & McKenzie. *Health Promotion & Education Research Methods* . 2005.

::: notes
There's more to say about this. Whatever type of research problem you tackle, the most important thing is that it has to be interesting to you. You're going to be spending a fair amount of your life on this.

Don't let your enthusiasm blind you, however. Get feedback from others.

Contribution to the profession addresses the "so what" question. Is it going to be publishable. You shouldn't be obsessed about publication, but it is a marker of whether the problem is considered important to others besides yourself.
:::

## Do nots

-   What should NOT drive picking a research question
    -   A specific research methodology
    -   A specific funding opportunity
    -   A publication-focused motivation
        -   But always publish your work.

::: notes
Don't get stuck in a rut with a single research methodology. Pick the methodology that most closely matches the needs of the research.

Funding is great, but don't fit your square research idea into a round funding hole.

Publications are important, but the goal is not publication but making a substantive contribution to the field.

Think about what happens if the results do not turn out they way you "want" them to. There is a myth that researchers are fully disinterested, but you have to think about your responsibilities of sharing information even if it is not what you wanted. Besides, you have done a disservice to those volunteers who helped you with the study. They gave up their Saturday morning cartoons (what's that new one: Square Bob Sponge something?) to help you with your research and they didn't do it for you. They did it for the benefit of patients like themselves.
:::
