---
title: "Comments for MEDB 5510, Week 02"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "Steps in research"
  topic_02: "Identify a research problem"
  topic_03: "Developing a research hypothesis"
  topic_04: "Historical overview of research ethics"
  topic_05: "IRB approval"
  topic_06: "Ethical issues"
editor: source
---

## Topics to be covered

```{r}
# Preliminaries, if needed

# Keep this chunk, even if no code, so that
# params is populated from the yaml header.

# To print speaker notes, add
#   ?print-pdf&showNotes=separate-page 
#   to the end of the URL. Then open the
#   print dialog box (ctrl-P) and choose
#   Save as PDF for the printer. Other 
#   options, like Microsoft Print to PDF
#   do not seem to work.
```

-   What you will learn
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`

::: notes
Here are your objectives.

We are going to talk about planning and ethics. We are going talk more about the variety of research that can be conducted. We'll introduce new dichotomies and we're going to describe what's needed to identify research question.

Now, in the short amount of time, we really can't do justice to ethics. We have an entire course, Ethical Conduct of Research that covers all the issues in greater detail. What I hope to do is to review a few basic issues and discuss the historical events associated with the increasing concern and demand for oversight. 
:::

{{< include _crm-02-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

{{< include _crm-02-02.qmd >}}

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`
    
{{< include _crm-02-03.qmd >}}

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`
    
{{< include _crm-02-04.qmd >}}

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`

{{< include _crm-02-05.qmd >}}

## Break #5

-   What you have learned
    -   `r params$topic_05`
-   What's coming next
    -   `r params$topic_06`

{{< include _crm-02-06.qmd >}}

## Summary

-   What you have learned
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`

<!---
      You have to put the title down 
      here to override the titles of
      all the include files.
--->

---
title: "Comments for MEDB 5502, Week 02"
---