---
title: "See bottom of file for title"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "The two by two crosstabulaton"
  topic_02: "Test of equality of two proportions"
  topic_03: "R code for the test of equality of two proportions"
  topic_04: "Sample size calculations"
  topic_05: "R code for sample size calculations"
  topic_06: "Chi-squared test of independence"
  topic_07: "R code for the chi-squared test of independence"
  topic_08: "Odds ratios and relative risks"
  topic_09: "R code for odds ratios and relative risks"
  topic_10: "Your homework"
editor: source
---

## Topics to be covered

```{r}
# A small section of R code to kick start the params.
```

-   What you will learn
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`
    -   `r params$topic_09`
    -   `r params$topic_10`

{{< include _b1-13-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

{{< include _b1-13-02.qmd >}}

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`

{{< include _b1-13-03.qmd >}}

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`

{{< include _b1-13-04.qmd >}}

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`

{{< include _b1-13-05.qmd >}}

## Break #5

-   What you have learned
    -   `r params$topic_05`
-   What's coming next
    -   `r params$topic_06`

{{< include _b1-13-06.qmd >}}

## Break #6

-   What you have learned
    -   `r params$topic_06`
-   What's coming next
    -   `r params$topic_07`

{{< include _b1-13-07.qmd >}}

## Break #7

-   What you have learned
    -   `r params$topic_07`
-   What's coming next
    -   `r params$topic_08`

{{< include _b1-13-08.qmd >}}

## Break #8

-   What you have learned
    -   `r params$topic_08`
-   What's coming next
    -   `r params$topic_09`

{{< include _b1-13-09.qmd >}}

## Break #9

-   What you have learned
    -   `r params$topic_09`
-   What's coming next
    -   `r params$topic_10`

{{< include _b1-13-10.qmd >}}

## Summary
-   What you have learned
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`
    -   `r params$topic_09`
    -   `r params$topic_10`

<!---Put the title down here to override the include files.--->

---
title: "MEDB 5501, Module 13"
date: 2025-11-18
---