---
title: "Evaluation of the the Galleri test"
author: "Steve Simon"
format: 
  html:
    embed-resources: true
editor: source
---

## Introduction

A close relative sent me an article about a diagnostic test, Galleri, produced by a complany, Grail, that has shown some distressing results in a clinical trial. She wanted some comments from me.

Fair enough. I am never without an opinion. Keep in mind that I am not a doctor, not an MD doctor anyway. But the trial results hinge on some important statistical issues so I thought I could add some comments about what is going on.

The actual article, 

Rebeeca Robbins and Gina Kolata, Grail's Cancer Detection Test Fails in Major Study, The New York Times, 2026-02-20

is behind a paywall. My relative actually saw this when it was reprinted in the Kansas City Star. I can't link to the article, but let me quote liberally from it.

## Before I start, let me state my prejudices

I am not a doctor, but I believe that our medical system, at least in the United States tends to over diagnose, over medicate, and over treat. This is an opinion that I have developed over time by reading from the real experts. But let me just give a fair warning. I tend to be skeptical of medical claims, and this is based on more than just my opinion. But if you want to call this perspective of mine a prejudice, go ahead.

## A promising blood test

The concept behind the Galleri blood test was quite simple. Look for "miniscule shards of cancer DNA in the blood". if you find these shards, you can diagnose "more than 50 types of cancer, according to the company." This is a big deal. The Galleri test was given a shout-out by the Hims telehealth company in a Superbowl ad. To be situated among Pringles, Pepsi, and Bud Light says a lot.

You don't have to say Superbowl ad to know that there is a lot of money involved.

"Galleri has been sold in the United States since 2021 and costs $949. Even though the blood test is not yet approved by the Food and Drug Administration, the company markets it under a regulatory loophole that permits sales of certain tests without review. Very few insurers cover the test, so most people pay for it out of pocket. Grail said it had sold nearly half a million of the tests so far, including more than 185,000 last year."

There's still more to the money angle.

"The company lobbied heavily for the U.S. government to cover the test under Medicare. The spending package passed by Congress and signed into law by President Trump earlier this month authorized Medicare to cover cancer detection tests, and Galleri could be among those that qualify to receive the government’s approval."

## Here's where my skeptical alarms go off

So I'm seeing some problems right off the bat. The money angle has me nervous, but it's more than that. Using DNA markers in cancer diagnosis harkens back to a major scandal at Duke University. Another article,

Gina Kolata, How Bright Promise in Cancer Testing Fell Apart, The New York Times, 2011-07-07,

also behind a paywall, talks about looking at "gene patterns that would determine which drugs would best attack [a] particular cancer." The test got a lot of attention, but was shown to be worthless. But it also shined a light on a very general problem. This was not a one-off. 

"The episode is a stark illustration of serious problems in a field in which the medical community has placed great hope: using patterns from large groups of genes or other molecules to improve the detection and treatment of cancer. Companies have been formed and products have been introduced that claim to use genetics in this way, but assertions have turned out to be unfounded. While researchers agree there is great promise in this science, it has yet to yield many reliable methods for diagnosing cancer or identifying the best treatment."

The fact is that it is hard to use DNA in a reliable way to diagnose or treat patients. It's being done with some success, but with just as many failures, it seems.

## But Grail ended up doing the right thing

Grail decided to subject their Galleri test to a rigorous randomized trial.

"The study enrolled 142,000 healthy adults ages 50 to 77 in Britain and followed them for three years. People had their blood drawn three times, each spaced about a year apart. One group of participants’ blood samples were run through the Galleri test, and those people were referred for medical care if they tested positive. The company compared the group that underwent Galleri screening with another group that didn’t get the test."

There are lots of ways to evaluate a diagnostic test, but many of the approaches have limitations. The randomized trial is one of the best ways to go, but it is expensive.

## The choice of the outcome measure



trial


This test was shown to be 




