---
title: "05-08, Homework"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## simon-5501-05-directions.md, 1

```{r hw0}
fn <- "simon-5501-05-directions.md"
template <- read_lines(file=fn)
h <- str_which(template, "##")
chunk_beg <- c(1, h)
chunk_end <- c(h-1, length(template))
```

```{r hw1}
cat(template[chunk_beg[1]:chunk_end[1]], sep="\n")
```

:::notes
Here is your homework assignment.
:::

## simon-5501-05-directions.qmd, 2

```{r hw2}
cat(template[chunk_beg[2]:chunk_end[2]], sep="\n")
```

:::notes
H.
:::

## simon-5501-05-directions.qmd, 3

```{r hw3}
cat(template[chunk_beg[3]:chunk_end[3]], sep="\n")
```

:::notes
L.
:::

## simon-5501-05-directions.qmd, 4

```{r hw4}
cat(template[chunk_beg[4]:chunk_end[4]], sep="\n")
```

:::notes
Use the read_tsv function when your data uses tab delimiters.
:::

## simon-5501-05-directions.qmd, 5

```{r hw5}
cat(template[chunk_beg[5]:chunk_end[5]], sep="\n")
```
:::notes
T. 
:::

## simon-5501-05-directions.qmd, 6

```{r hw6}
cat(template[chunk_beg[6]:chunk_end[6]], sep="\n")
```

:::notes
T.
:::

## simon-5501-05-directions.qmd, 7

```{r hw7}
cat(template[chunk_beg[7]:chunk_end[7]], sep="\n")
```

:::notes
T.
:::

## simon-5501-04-gardasil.qmd, 8

```{r hw8}
cat(template[chunk_beg[8]:chunk_end[8]], sep="\n")
```

:::notes
T.
:::

## simon-5501-04-gardasil.qmd, 9

```{r hw9}
cat(template[chunk_beg[9]:chunk_end[9]], sep="\n")
```

:::notes
T.
:::
