---
title: "Heterogeneity"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Too much heterogeneity is bad

-   Mixing apples and oranges
-   Example: statins
    -   Primary versus secondary prevention
    
::: notes
Meta-analyses should not have too broad an inclusion criteria. Including too many studies can lead to problems with "apples-to-oranges" comparisons. For example, when you are studying the effect of cholesterol lowering drugs, it makes no sense to combine a study of patients with recent heart attacks with another study of patients with high cholesterol but no previous heart attacks.

There is a lot of variability in how research is conducted. Even in carefully controlled randomized control trials, researchers have tremendous discretion (Am J Med 1987: 82(3); 498-510.). Sometimes this discretion creates heterogeneity among studies, making it difficult to combine the studies.
:::

## Heterogeneity in patient populations

-   Demographics of patients
-   Exclusion critieria
-   Baseline health

::: notes
You might see heterogeneity in the composition of the treatment and control groups. The patients may be older or younger. They may have different race and ethnicity proportions.

Researchers can differ in the inclusion and exclusion criteria.

Even if these criteria do not differ, there may still be differences in the baseline levels of health in the patients, due to geographical differences in the patient population.
::: 

## Heterogeneity in sampling

-   Independent versus matched samples
-   Type of control
-   Type of treatment

::: notes
The controls could be selected independently, or they could be matched to the treatment group subjects.

The control subjects could be given no treatment, a placebo, or a standard treatment.

The treatment could differ, such as differences in dose or timing of a drug.
:::

## Heterogeneity in study design

-   Length of follow-up
-   Drop-out rates

::: notes
Heterogeneity in the design of the study

The length of follow-up for the patients could differ.

The proportion of patients who drop out could differ as well as the proposed statistical treatment of these dropouts.
:::

## Heterogeneity in patient management 

-   Treatment of comorbid conditions
-   Handling of complications
-   Physician discretion

::: notes
Heterogeneity in the management of the patients and in the outcome

How comorbid conditions are treated. Can patients take a variety of medicines unrelated to the study?

How complications are handled. Do patients with complications stay in the study and if so, what treatment options are allowed.

How much discretion the patient's physician has in controlling patient care. Some studies allow a wide degree of discretion in treatment but others are very detailed in what the physician is allowed to do. If a physician in these studies sees a need for something that is not allowed, the patient has to be dropped from the study.
:::

## Heterogenity in outcome measures

-   Example: hypertension treatment
    -   cardiovascular deaths
    -   cardiovascular events
    -   cerebrovascular deaths
    -   cerebrovascular events
    -   deaths due to any cause
    
::: notes
The outcome measure itself could differ. For example, Abramson (Public Health Rev 1990: 18(1); 1-47) discusses a meta-analysis of hypertension treatment in the elderly. Some of the studies examined cardiovascular deaths and others examined cardiovascular events. Other studies examined cerebrovascular deaths, cerebrovascular events, cardiac deaths, coronary heart disease deaths, and/or total deaths.
:::

## Examples of heterogeneity

-   Antiretroviral combination therapy
    -   Effective in shorter trials
    -   Ineffective in longer trials
-   Dust mite control measures    
    -   Chemical or physical interventions
    -   Crossover or parallel design
    -   Variation in blinding
    -   Age of patients
    -   Duration of trial
    
::: notes
In a meta-analysis (BMJ 2002; 324(7340): 757) looking at antiretroviral combination therapy, a plot of duration of trial versus the log odds ratio showed that shorter duration trials of zidovudine had substantial evidence of effect (odds ratios much smaller than 1) but that the largest duration studies had little or no evidence of effect (odds ratios very close to 1).

In a meta-analysis (BMJ 1998: 317(7166); 1105-1110) looking at dust mite control measures to help asthmatic patients, the studies exhibited heterogeneity across several factors. Six studies examined chemical interventions, thirteen examined physical interventions, and four examined a combination approach. Nine of these trials were crossovers, and in the remaining fourteen, there was a parallel control group. Seven studies had no blinding, three studies had partial blinding, and the remaining thirteen studies used a double blind. In nine studies the average age of the patients was only 9 or 10 years, but nine other studies had an average age of  30 or more. Eleven studies lasted eight weeks or less and five studies lasted a full year. You can find a table summarizing these studies on the web.
:::

## How to handle heterogeneity

-   Some heterogenity is actually encouraged
-   Subgroup analysis
-   Meta-regression

::: notes
Some level of heterogeneity is acceptable. After all, the purpose of research is to generalize results to large groups of patients. Furthermore, demonstrating that a treatment shows consistent results across a variety of conditions strengthens our confidence in that treatment.

Nevertheless, you should be aware of the problems that excessive heterogeneity can cause. Mixing apples and oranges may not be so bad; you get a fruit salad this way. But when heterogeneity becomes too large, you might end up combining not apples and oranges but apples and onions.

Subgroup analysis

When there is substantial heterogeneity, you can look and compare subgroups of the studies. In a meta-analysis (BMJ. 2000; 321(7273): 1371-6) studying atypical antipsychotics, the dose of the comparison drug (haloperidol or an equivalent) varied substantially. Among those studies where the dose of haloperidol was greater than 12 mg/day, atypical antipsychotics showed advantages in efficacy or tolerability. When the dose was less than or equal to 12 mg/day, the atypical antipsychotics showed no advantages in these areas.

Meta-regression

You can try to adjust for heterogeneity in a meta-analysis. This would work very similarly to the adjustment for covariates in a regression model. For example, Derry et al (BMJ 2000: 321(7270); 1183-7) used meta-analysis to see if long term aspirin therapy was associated with problems with gastrointestinal hemorrhage. They identified 24 studies that looked at aspirin as a preventive measure against heart attacks. In each of these studies, the rate of gastrointestinal hemorrhages were recorded for both the aspirin group and the placebo or no treatment group. There was substantial heterogeneity in the dosage of aspirin used in the studies, however, with some studies giving as little as 50 mg/day and some as much as 1500 mg/day.

This was actually good news in a way, because the researchers wanted to see if the risk of gastrointestinal hemorrhage was dependent on the dose of aspirin. A plot of the dose versus the risk showed that there was indeed an increased risk but that this risk seemed to be unrelated to the dosage.
:::

## Inclusion of very old studies

-   Varies by discipline
-   Look for "game changing" events
    -   Surfactants in neonatology
    -   Anti-retrovirals for HIV patients
    -   Fluouridation of water supplies

::: notes

The time frame depends a lot on the topic. Anything in the field of neonatology would have to have a very narrow time window because the field has changed so much so rapidly.

Other areas where the practice of medicine has been much more stable could have wider time windows. I've seen several reviews that have covered half a century of studies.

If you do select a wide time window be sure to see if your results are similar if you restrict yourself to just the most recent studies.

Ask yourself if there was a sudden change in technology that makes any comparisons before and after that technology an apples-to-oranges comparison. So, for example, a meta-analysis involving AIDS patients should restrict itself to the years following the use of AZT.

Also, ask yourself if researchers in your area tend to discount any research that is more than X years old. If so, then your meta-analysis would lose credibility among those researchers if it included studies older than X.
:::

## Test of heterogeneity

-   Cochran's Q
    -   Null hypothesis: homogeneity
    -   Reject if chi-square statistic much larger than degrees of freedom
-   I-squared
    -   Descriptive measure
    -   Always between 0% and 100%
    -   Below 25% implies homogeneity
