---
title: "MEDB 5510, Clinical Research Methods, Objectives for every module"
output: 
  powerpoint_presentation:
    slide_level: 2
---

```{r read01, echo=FALSE}
suppressMessages(
  suppressWarnings(
    library(tidyverse)))
excerpt <- function(n) {
  '5510-xx-overview.md'                  %>%
    str_replace('xx', '01')              %>%
    read_lines                           %>%
    paste0(collapse='\n')                %>%
    str_split('####')                    %>%
    unlist                                -> sections
  paste0(
    '## Module', n, 
    ', ',
    sections[3],
    '<div class="notes">',
    '\n\n',
    sections[2],
    '\n\n',
    '</div>')
}
```

`r excerpt("01")`

## Module02

```{r, child="5510-02-objectives.md"}
```

<div class="notes">

```{r, child="5510-02-synopsis.md"}
```

</div>

## Module03

```{r, child="5510-03-objectives.md"}
```

<div class="notes">

```{r, child="5510-03-synopsis.md"}
```

</div>

## Module04

```{r, child="5510-04-objectives.md"}
```

<div class="notes">

```{r, child="5510-04-synopsis.md"}
```

</div>

## Module05

```{r, child="5510-05-objectives.md"}
```

<div class="notes">

```{r, child="5510-05-synopsis.md"}
```

</div>

## Module06

```{r, child="5510-06-objectives.md"}
```

<div class="notes">

```{r, child="5510-06-synopsis.md"}
```

</div>

## Module07

```{r, child="5510-07-objectives.md"}
```

<div class="notes">

```{r, child="5510-07-synopsis.md"}
```

</div>

## Module08

```{r, child="5510-08-objectives.md"}
```

<div class="notes">

```{r, child="5510-08-synopsis.md"}
```

</div>

## Module09

```{r, child="5510-09-objectives.md"}
```

<div class="notes">

```{r, child="5510-09-synopsis.md"}
```

</div>

## Module10

```{r, child="5510-10-objectives.md"}
```

<div class="notes">

```{r, child="5510-10-synopsis.md"}
```

</div>

## Module11

```{r, child="5510-11-objectives.md"}
```

<div class="notes">

```{r, child="5510-11-synopsis.md"}
```

</div>

## Module12

```{r, child="5510-12-objectives.md"}
```

<div class="notes">

```{r, child="5510-12-synopsis.md"}
```

</div>

## Module13

```{r, child="5510-13-objectives.md"}
```

<div class="notes">

```{r, child="5510-13-synopsis.md"}
```

</div>

