---
title: "Ethical issues"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Ethical issues

-   Conflict of interest
-   Unfavorable risk/benefit ratio
-   Loss of equipoise
-   Deception
-   Violating privacy

::: notes
Here's a brief list of ethical issues that you may confront as you are planning your research. These should be thought about well before you make your submission to the IRB. In particular, you may want to change your research approach if that change helps you avoid some of these ethical challenges.

Conflict of interest has gotten a lot of press, and I just want to emphasize a perspective that I have that is probably a minority perspective in the research community. A lot of people talk about non-financial conflicts of interest, but I believe (with only a few very rare exceptions) that only financial conflicts are important enough to warrant reporting.

Financial conflicts of interest are real and there is solid empirical evidence of their biasing effects. A financial conflict of interest does not bar you from doing the research, but it usually requires you to have a greater degree of oversight. A Data Safety and Monitoring Board, for example, might be appointed to make calls about whether a research study needs to be ended early because your financial investment in the research might create at least the appearance of bias in that decision.

The risk/benefit ratio is tricky, and we do allow for setting where someone can endure pain, suffering, and increases in the risk of bad outcomes, as long as these are minimal and well controlled. Even when the risks are very small, you may get in trouble if there is little or no benefit to your research.

Equipoise is a very controversial topic. There are varying definitions, but I like the one that defines equipoise as "genuine uncertainty in the expert medical community  over whether a treatment will be beneficial." (quoted from the Wikipedia page on clinical equipoise) This does not imply a perfect balance. Equipoise will help you determine whether use of placebos is acceptable, for example, and there is a lot of debate about placebos. I can't share all the details of this area today, but ask me if you are curious about anything involving equipoise or placebos, as I have written a lot about this on my website and blog.

If you can't deny a well-established treatment to your control arm, then sometimes (but only sometimes) you can offer a waiting list control group. Everybody gets the treatment, but a randomly selected number of patients have to wait a certain amount of time before receiving the treatment. Also, you can fashion your trial as an add-on design. Everybody gets the best known available therapy, but some get a new, but unproven, therapy and others get a placebo in place of the therapy.

Deception is part of many research studies, especially in Psychology, but it needs to be done carefully. You can deceive people about the purpose of a research study if their knowledge about the purpose would change their behavior in a way that would invalidate the research. If you use deception in a study, you have to "fess up" during a debriefing session after the research is done. You can never deceive a research subject about the risks of the research.

Privacy violations are a big and growing concern in research. You should try to avoid storing private information if you can. If you do have to store private information, keep it in a secure location. USB sticks or the local hard drive on your computer are not secure because these are sometimes lost or stolen. If you must use these media, then use encryption. It is much better to store private information on a network folder because this is protected by your password and the physical storage devices are kept behind locked doors. Note that HIPAA has serious civil and criminal penalties for the accidental disclosure of private health information.
:::

## Ethical concerns in animal studies

-   Review by IACUC.
    -   Mandated by Animal Welfare Act and USDA regulations
    -   Live vertebrate animals
    -   Sample size justification

::: notes
Animal studies at UMKC are review by the Institutional Animal Care and Use Committee (IACUC). This is mandated by federal law and US Department of Agriculture regulations.

It only applies to live vertebrate animals, so dissections don't count and research on flatworms does not count.

You have to take proper care of research animals and minimize to the greatest extent possible their pain and suffering.

The IACUC is going to take a very careful look at the sample size justifications for your animal research. Both too many and too few animals will raise concerns. We'll talk about sample  size justification later in this class.
:::


## Fraud in research

-   Fraud falls into three broad categories (FFP).
    -   Fabrication
    -   Falsification
    -   Data alteration
    -   Misreporting
    -   Plagiarism.
-   Note: A difference of scientific opinion does not mean that one party is behaving fraudulently.

::: notes
I hesitate to talk about fraud because I know all of you are honest. But you need to know what fraud is, because you may encounter it in your interactions with others.

Fraud falls into three major categories: fabrication, falsification, or plagiarism. 

Fabrication is the wholesale invention of data, which falsification means alteration of existing data or withholding or misrepresentingin important details of your research in a presentation or publication. This means details that are important enough to change how people few the validity of your research. In particular, if you change how you originally planned to collect or analyze your data, and you don't not this as a post hoc change in your protocol, you could be accused of fraud.

Plagiarism is the use of other peoples words or ideas without their permission and without proper attribution.

We'll talk about appropriate actions that you should take if you suspect fraud in just a bit.
:::


## Research misconduct (other than fraud)

-   Inappropriate authorship
    -   Ghost writing
    -   Leaving off deserving authors
    -   "Honorary" authorship
-   Violation of confidentiality
-   Sabotage

::: notes
There are other forms of research misconduct that do not officially constitute fraud but which are still important. Ghost writing, which means writing done by someone who is deliberately kept off the list of authors to avoid conflict of interest disclosures is a big no-no and might rise to the level of fraud. When you publish a paper you have to make sure that everyone who deserves co-authorship is included. You should not leave someone off who made a material contribution to the planning, analysis, or writing. On the other hand, you should not include someone based solely on their reputation or their supervisory role. Finally, do not include someone as a co-author on your paper without getting their permission first.

You are also subject to various confidentiality requirements when you are reviewing other people's work, such as through the peer-review process of a medical journal. Although this is not under the direct purview of the IRB, it is still important that you do not share research information that you have vowed to keep private.

I have never seen it, but there have been reports of scientists who deliberately sabotage other people's work. The motivations for this vary: it could be professional jealousy or it could be a desire to be the first with a new finding.
:::


## Whistle blowing

-   Failure to report research misconduct is research misconduct
-   No retaliation for legitimate complaints.

::: notes
When you witness research misconduct, you have an obligation to report it. Failure to report research misconduct is itself research misconduct. This is very difficult, of course, if you find yourself in a position subordinate to the person who is behaving badly.

There are protections for whistleblowers, but that does not always protect you against retaliation. I've never found myself in a situation where I have observed research misconduct, so I can't offer too much advice.
:::


## Whistle blowing

-   There is more than one avenue for reporting misconduct
    -   Do nothing.
    -   Talk with the person directly.
    -   Talk to some of your peers.
    -   Talk with your own supervisor.
    -   Talk to a person higher up in the organizational structure
    -   Report a complaint anonymously.

::: notes
If you experience something that you feel is not right, you have the option of doing nothing. That's a risky option, but if you feel that all the other options are riskier, I, for one, would understand. Depending on the dynamics, you might consider talking to the offending party directly. You might ask your peers or your own supervisor (assuming that they are not parties to the misconduct allegation) or someone higher up in the organizational structure than the offending party. Most organizations have an ombudsperson who you can talk to. An ombudsperson will never divulge information without your permission. Your organization may also have other anonymous reporting avenues.

If you do talk to someone, please be open to the possibility that you may just be misunderstanding the situation.
:::


## Research Ethics 

-   NIH definition (NIH Catalyst, 2001)
    -   Fabrication
        -   inventing data or results
    -   Falsification
        -   manipulating research materials, equipment, or processes, or changing or omitting data or results
    -   Plagiarism
        -   appropriation of ideas, processes, results, or words of another person without giving appropriate credit

::: notes
Uniform definition: fabrication, falsification, plagiarism.

Note that when you review a paper or grant, You cannot use any ideas, words, results, or processes from that paper or proposal.

Example of NIH report of research misconduct.

The penalties are fairly severe.
:::


## Research Ethics 

-   Training
    -   CITI training - used by multiple institutions
-   IRBs
    -   UMKC IRB
    -   IRBs at other institutions (CMH, St. Luke's)
-   Research committees

::: notes
Training is an important institutional imperative for anyone involved with research.
:::
