---
title: "Historical overview of research ethics"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Landmarks in research ethics

-   Nuremberg code (1947)
-   Declaration of Helsinki (1964)
-   Belmont report (1978)
-   Title 45 of the Code of Federal Regulations, Part 46 (1981)
-   Health Insurance Portability and Accountability Act (1996)

::: notes
We have an entire course devoted to the ethical conduct of research. I just want to touch on a few issues that you need to think about during the planning phase of your study.

It helps to have a brief understanding of some of the historical milestones in research ethics.

The Nuremberg code was developed in 1947. It is a bit dated today, but it's very brief and worth reviewing to understand some of the foundations that underlie more recent work.

The Declaration of Helsinki (1964, with modifications over the years) provided a modern and more workable framework for research. It is very brief, but provides a surprising amount of guidance. The document places a strong emphasis on scientific integrity. This means you don't do research unless it has an important goal). It also stresses the rights of research subjects. They have to provide informed consent and can withdraw at any time. The document also stresses the responsibilities of the researcher. You have to weights costs and benefits and always provide the best available care, even in the control group.

The Belmont report, written in 1976 by the National Commission for the Protection of Human Subjects was mandated by the National Research Act of 1974. It lays out a foundation for ethical research, based on respect for persons, beneficence, and justice. It's a long read, unfortunately, and you may prefer to read some written summaries instead.

It led to the development in 1981 (updated in 1991) of federal regulations (title 45 of the Code of Federal Regulations, Part 46, affectionately nicknamed 45 CFR 46 or the common rule). These are written in "lawyerese". Again a summary is helpful, and you might only need to refer directly to these regulations to settle an argument. Note that there are discrepancies between the requirements for NIH versus FDA research. This document outlined the structure and function of an Institutional Review Board (IRB), and offered special protections for vulnerable populations.

IRBs were established to review research to insure that the rights of the participants is protected. They must have at least five members, mix of gender, race/ethnicity, background. At least one member must be from the general public. In some people's eyes, IRBs serve only to delay research and to destroy the scientific value of research. There is some truth in this perhaps, but it is much to cynical a perspective. Think of the IRB as an ally who can help insure that your research plan is appropriate and most importantly publishable. Research that fails to comply with the regulatory requirements will not survive peer review, so it is better to fix things now rather than wait until the project is over to find that there are ethical flaws that block the dissemination of your research.

The Health Insurance Portability and Accountability Act of 1996 recognized the flow of health information through computerized systems and provided privacy protection for those records.
:::

## Landmarks in research ethics

-   Pure Food and Drugs Act (1906)
-   Federal Food, Drug, and cosmetic Act (1938)
-   Kefauver Harris amendments (1962)
-   FDA Modernization Act (1997)
-   Best Pharmaceuticals for Children Act (2002)

::: notes
Note: Add discussion of 21 CFR 56 (https://www.fda.gov/science-research/good-clinical-practice-educational-materials/comparison-fda-and-hhs-human-subject-protection-regulations) and ICH (1990, https://www.ich.org/page/history).

The regulatory framework for testing of drugs evolved over a different time frame.

Much of the research that the Food and Drug Association mandates today originate from a 1906 law intended to apply proper labeling standards to food and drugs.

The Food and Drug Cosmetic Act of 1938 further required that all new drugs be tested for safety. The law was passed after a tragedy involving the deaths of more than 100 people who had taken a drug, Eleixir slfanilamide, that caused acute kidney failure. 

The Estes-Kefauver amendments of 1962 were written in response to the Thalidomide tragedy, where an anti-nausea medication was given to pregnant women and resulted in numerous birth defects. The acts required that new drugs had to show efficacy in addition to safety before they could be approved for use in humans.

The FDA Modernization Act of 1997 provided a framework for drug companies to establish off-label uses (uses not authorized in the original drug approval process) and established a framework for regulation of medical devices.

The Best Pharmaceuticals for Children Act was passed in 2002 to encourage pediatric studies by offering an additional six months of patent protection to certain drugs if these studies were conducted.
:::
