---
title: "14-02 Review of modules 03 and 04"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Module 03

-   What is a literature review?
-   Finding sources for your literature review
-   Summarizing and evaluating individual articles

## Module 03

-   An organizing structure to your literature review
    -   Chronological
    -   General to specific
    -   Themes

::: notes

Some possible themes:

Consensus, disagreements, the unknown

Problem, old remedies, new needs

Supportive, then non-supportive

Methodologies

Theories

Schools of thought

:::

## Module 03

-   Writing a methods section
    -   Participants
    -   Materials
    -   Procedures
    -   Measures
    -   Analysis
-   Talking about your research

## Module 04

-   Experimental, quasi-experimental, observational studies
-   How to randomize
-   Advantages and disadvantages of randomization
-   Alternatives to randomization
-   Blinding
-   Intention to treat analysis
-   Baseline measures
