---
title: "Community-Based Participatory Research"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Problems with traditional research {.smaller}

-   "Researchers are like mosquitoes; they suck your blood and leave" from Cochran 2008.
-   Harms of research
    -   Stigmatization
    -   Condescension
    -   Reinforcement of stereotypes
    -   Cultural insensitivity
    -   Failure to respect community standards
    -   Abandonment when the research is done
    -   Deception about true research purpose

::: notes

I'm going to have some harsh words for you now, but you need to hear them. Researchers don't always make the world a better place.

There is an increasing recognition that research often tends to benefit the person doing the research, and not the people who participate in the research. In fact, sometimes the research harms the participants, through stigmatization, condescending attitudes, and the reinforcement of harmful stereotypes. Researchers have abused their position by deceiving the research participants about the true goal of the research. They often fail to recognize and respects standards within the communities that they conduct their research in. There is also often a sense of abandonment, once the research is done, the participants never see or hear anything about the work.

This is not true about all research and all researchers. It isn't even true about most research, I hope. But it does happen much more often than it should and it "poisons the well" and makes future research more difficult.

:::

## What is Community Based Participatory Research (CBPR)?

-   Designed in collaboration with the people being researched
-   Also known as Participatory Action Research (PAR)
-   Not restricted to any research methodology

::: notes

Community Based Participatory Research (CBPR) is an effort to avoid many of these abuses by actively engaging the community in all aspects of the research from the planning to the conduct to the write-up of the results. It is also known by the acronym PAR (Participatory Action Research).

CBPR is not restricted to any particular type of research (e.g., qualitative versus quantitative), except that research in the community is, by definition, field research.

:::

## Disadvantages of CBPR

-   Designed in collaboration with the people being researched
-   Also known as Participatory Action Research (PAR)
-   Not restricted to any particular research methodology

::: notes

CBPR is not easy. It takes a lot more time. You need excellent communication skills, and especially listening skills.

It also will make you feel quite a bit uncomfortable. You will be working with people who are quite different than you are, who have different needs, and different values. And if you're like 90% of all researchers, you're an introvert to begin with. I'm sure that your comfort level will improve over time, but I've been told that getting started is quite awkward.

:::

## Advantages of CBPR

-   Advantages to you, the researcher
    -   Precisely targeted intervention
    -   Improved participation rate
    -   Greater generalizability
-   Advantages to the community
    -   Sustainability
    -   Greater community capacity

::: notes

There are several big advantages to you, the researcher. By involving the participants in the research planning, you will be better able to target your intervention to the specific needs of this particular community. Second, the people in the community who help you plan the research will know better than you do how to design your study to make it attractive for the research participants. This will greatly improve your participation rate. The process of involving the community will almost always place the research in a more naturalistic context, which improves your generalizability.

There are advantages to the community beyond just making you, the researcher, less arrogant. When the community makes a commitment to the research process this insures a better level of sustainability.

The community based process helps the community grow and develop more capacity for research (and research that actually benefits them). They know as little about your world as you know about theirs. They, like you, will learn new skills. This will help the community in their interactions with future researchers. 

:::


## Getting started with CBPR {.smaller}

-   Pick a problem 
    -   Simple
    -   Important
    -   Needed
-   Ideal settings
    -   Health disparities
    -   Complex interventions
-   Identify resources
-   Keep an open mind
-   Be willing to compromise

::: notes

If you are new to CBPR, start with something that is simple, important, and needed. Pick something that you know should add value to the community. 

CBPR has been applied effectively in health disparities research because often you are already doing quite well in some communities, but there are barriers in other communities that keep you from delivering a uniformly high quality of care. The community can help you identify and overcome those barriers.

CBPR is also ideal for complex interventions, because the community can help you package the components that are most important from their perspective.

Identify people who can be resources. Keep an open mind about the process. There is little value in insisting on a rigid approach. Also understand that compromise will be necessary. You need to sacrifice some of the things that you want in order to get the cooperation of people who have different goals than you do.

:::

## Emphasize your strengths

-   Things you know that they don't
    -   Existing research evidence
    -   Ability to diagnose
    -   Natural course and history of disease
    -   How to measure
    -   Research standards
  
::: notes

When you are working with a community, you can't be arrogant, but you can't hide your light under a bushel either. The community will look to you for your expertise. You know more than they do about what has been published in the literature. Your medical background makes you an expert in diagnosing disease, knowing what treatments are available, and what happens when a disease is left untreated.

You also have the advantage of understanding the standards of research, ESPECIALLY BECAUSE YOU HAVE HAD THE BENEFIT OF SUCH A GREAT TEACHER IN YOUR RESEARCH METHODS CLASS!!! You know about the need to measure carefully and objectively, the value of a control group, and how to prepare results that are persuasive in the research community.

:::

## Understand the strengths of the community members

-   Things that they know that you don't
    -   Specific needs of their community
    -   Where to find research volunteers
    -   What they will and will not tolerate
    -   How to tweak an intervention
    -   Pragmatic advice

::: notes

What you are looking for in the community is insights into the local context. The community knows best what their specific needs are and can help you prioritize. They know where to find volunteers, and can tell you what they will do and what they will refuse to do. They know how to adapt your proposed intervention to the special features of their community. In general, they offer very pragmatic advice about how to make a good fit between your research and their community.

:::

