---
title: "Clinical Research Methods, Overview for Module 2"
author: "Steve Simon"
output:
  html_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, 
    encoding=encoding,
    output_dir = "../results", 
    output_format = "all") })  
---

Created: 2020-02-07

Updated: `r Sys.Date()`

This is a list of assignments, readings, and discussion questions for module02. **If you notice a discrepancy between this overview and what appears on the Canvas website, please contact me. But do note that the Canvas website always takes precence over this overview.**

```{r child="../data/objectives02.md}
```

You can find the recommended readings [here](https://umkc.instructure.com/courses/66239/pages/all-modules-recommended-readings).

### Videos and handouts

Please view the 2021 recording and only look at the 2019 if you are curious. Students who attended the live lecture on Wednesday do not have to view either recording, unless they want to.

+ V02-01, Steps in a research project
  + 2021 recording available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c2600686-dc98-49e0-a715-acbe0110bd89).
  + 2019 recording available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d48d6a7d-82d4-495b-900b-a9e3016a2c93).
  + Slides and speaker notes available in [pdf format](https://github.com/pmean/classes/blob/master/clinical-research-methodology/results/video02-slides-and-speaker-notes.pdf).
+ V02-02, Choosing a good research problem
  + 2021 recording available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=42809abf-1908-4cdd-aa01-acbe0133a698).
  + 2019 recording available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d9dbdf71-7aa7-43f4-8cc4-a9e3016fac76).
  + Slides and speaker notes, see above
+ V02-03, Developing a research hypothesis
  + 2021 recording available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=1c334cbc-0f91-40f9-9ee1-acbe01560869).
  + 2019 recording available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=22995d36-b9e8-443d-8283-a9e30176a0c9).
  + Slides and speaker notes, see above
+ V02-04, Research ethics
  + 2021 recording available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=46510b84-3aac-439b-9e7c-acbe015e321b).
  + 2019 recording available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d291c2c0-965a-4d28-a375-a9e3017ebd80).
  + Slides and speaker notes, see above
+ V02-05, Homework for module02
  + 2021 recording available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d23930ef-6931-41bb-93f0-acbe016935a2).
  + There is no 2019 recording of the homework assignment
  + Live demo, no slides available