---
title: "Video 00 - Course overview"
author: "Steve Simon"
output: 
  powerpoint_presentation:
    reference_doc: ../doc/template.pptx
    slide_level: 3
---

```{r echo=FALSE}
source(file="prelims.R", echo=FALSE)
```

***
`r read_text("syllabus-course-instructor")`

<div class="notes">

Here is a brief overview of my syllabus. Please read this carefully on your own. I am part-time and do a fair amount of work at home, so email is the best way to contact me.

</div>

***
`r read_text("syllabus-course-catalog")`

<div class="notes">

This is a three credit hour class.

</div>

***
`r read_text("syllabus-course-description")`

***
`r read_text("syllabus-course-topics")`

***
`r read_text("syllabus-introduction")`

Note: Many thanks go to Dr. Mary Gerkoich, who provided an excellent structure and format to this class that I will be following closely. 

***
`r read_text("syllabus-course-objectives")`

***
`r read_text("syllabus-course-objectives1")`

***
`r read_text("syllabus-course-requirements")`

***
`r read_text("syllabus-course-framework")`

***
`r read_text("syllabus-course-structure")`

***
`r read_text("syllabus-course-required-materials")`

***
`r read_text("syllabus-course-recommended-materials")`

***
`r read_text("syllabus-course-resources")`

***
`r read_text("syllabus-course-evaluation")`

***
`r read_text("syllabus-assignments-schedule")`

***
`r read_text("syllabus-assignments-evaluation")`

***
`r read_text("syllabus-assignments-grading")`

***
`r read_text("syllabus-assignments-submission")`

***
`r read_text("syllabus-assignments-discussion-overview")`

***
`r read_text("syllabus-assignments-discussion-evaluation")`

***
`r read_text("syllabus-assignments-assessment")`

***
`r read_text("syllabus-assignments-weekly")`

***
`r read_text("syllabus-assignments-quizzes")`

***
`r read_text("syllabus-project-overview")`

***
`r read_text("syllabus-project-presentation")`

***
`r read_text("syllabus-project-poster-material")`

***
`r read_text("syllabus-project-poster-structure")`

***
`r read_text("syllabus-project-proposal", wed[16])`

***

***
`r read_text("syllabus-policies-canvas")`


***
`r read_text("syllabus-policies-email")`

***
`r read_text("syllabus-policies-discussion")`

***
`r read_text("syllabus-policies-conduct")`

***
`r read_text("syllabus-policies-honesty")`

***
`r read_text("syllabus-policies-attendance")`

***
`r read_text("syllabus-policies-discrimination")`

***
`r read_text("syllabus-policies-english-proficiency")`

***
`r read_text("syllabus-policies-grade-appeal")`

## Week 1: Course Overview and Introductions; Introduction to Clinical Research Methods

`r read_text("objectives01")`

## Week 2: Planning a Research Project, Introduction to Key Concepts, Research Ethics

`r read_text("objectives02")`

## Week 3: Literature Reviews, Library Resources

`r read_text("objectives03")`

## Week 4: Analysis of Secondary Data Sets

`r read_text("objectives04")`

## Week 5: Research Approaches / Designs, Randomized Experimental and Quasi-experimental Designs

`r read_text("objectives05")`

## Week 6: Non-experimental Approaches and Designs

`r read_text("objectives06")`

## Week 7: Internal Validity, Sampling and Introduction to External Validity

`r read_text("objectives07")`

## Week 8: Measurement and Descriptive Statistics

`r read_text("objectives08")`

## Week 9: Measurement Reliability and Validity

`r read_text("objectives09")`

## Week 10: Types of Data Collection Techniques, Practical Issues in Data Collection and Coding

`r read_text("objectives10")`

## Week 11: Spring break

## Week 12: Data Analysis and Interpretation

`r read_text("objectives12")`

## Week 13: Data Analysis for Clinical Research

`r read_text("objectives13")`

## Week 14: Writing a Research Proposal, Writing Up the Research Project, Final Project

`r read_text("objectives14")`

## Week 15: Evaluating Research

`r read_text("objectives15")`

## Week 16, Oral Presentations

`r read_text("objectives16")`

