---
title: "10-00, Resources needed for module 10 slides"
format: 
  html:
    embed-resources: true
editor: source
---

```{r 10-00-setup}
#| message: false
#| warning: false
library(magrittr)
library(tidyverse)
library(yaml)
```

## Data dictionary 1, part 1

```{r dd-1-1}
f1 <- "https://raw.githubusercontent.com/"
f2 <- "pmean/data/main/files/"
f3 <- "wolf-river-pollution.yaml"
yaml_text <- read_yaml(paste0(f1, f2, f3))

dictionary_1a <- 
	setdiff(names(yaml_text), "vars")
n <- length(dictionary_1a)
dictionary_1a
```

## Data dictionary 1, part 2

```{r dd-1-2}
dictionary_1b <- rep(" ", n)
for (i in 1:n) {
  dictionary_1b[i] <- 
    as.yaml(
      yaml_text[
        dictionary_1a[i]])
}
dictionary_1b <- paste0(dictionary_1b, "\n")
dictionary_1b[1]
length(dictionary_1b)
```

## Data dictionary 1, part 3

```{r dd-1-3}
dictionary_1c <- names(yaml_text$vars)
m <- length(dictionary_1c)
dictionary_1c
```

## Data dictionary 1, part 4

```{r dd-1-4}
vars_text <- yaml_text$vars
dictionary_1d <- rep(" ", m)
for (i in 1:m) {
  dictionary_1d[i] <- 
    as.yaml(
      vars_text[
        dictionary_1c[i]])
}
dictionary_1d <- paste0(dictionary_1d, "\n")
dictionary_1d[1]
length(dictionary_1d)
```

## Code-1

```{r 10-00-code-river}
fn <- "simon-5501-10-river.qmd"
code_text <- read_lines(file=fn)
chunk <- 
	cumsum(
	  str_detect(
	  	code_text, "## "))
data.frame(code_text, chunk) |>
	group_by(chunk) |>
	summarize(
		chunk_text =
			paste0(
				code_text, 
				sep="\n", 
				collapse="")) |>
	pull(chunk_text) -> code_1
code_1 <- paste0(code_1, "\n")
cat(code_1[1])
length(code_1)
```

## Programming assignment

```{r 10-00-prog-text}
fn <- "simon-5501-10-directions.md"
prog_text <- read_lines(file=fn)
chunk <- 
	cumsum(
	  str_detect(
	  	prog_text, "## "))
data.frame(prog_text, chunk) |>
	group_by(chunk) |>
	summarize(
		chunk_text =
			paste0(
				prog_text, 
				sep="\n", 
				collapse="")) |>
	pull(chunk_text) -> directions_1
cat(directions_1[length(directions_1)])
length(directions_1)
```

## Read the flicker data

```{r 10-00-flicker}
eye <- read_tsv(
  file="../data/flicker.txt",
  col_names=TRUE,
  col_types="cn")
names(eye) <- tolower(names(eye))
glimpse(eye)
```

```{r 10-00-read-river}
river <- read_tsv(
  file="../data/wolf-river-pollution.txt",
  col_names=TRUE,
  col_types="cnn")
names(river) <- tolower(names(river))
glimpse(river)
```

## Condense

Eventually, I want to combine chunks as long as the number of lines does not exceed a specified number 

## Save everything important

```{r 10-00-save}
save(
	dictionary_1a,
	dictionary_1b,
	dictionary_1c,
	dictionary_1d,
	code_1,
	directions_1,
	eye,
	river,
	file="../data/module10.RData")
```
