---
title: "r-01-01, History of R"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Special note

+ This slide show was created using R.
  + Not complicated 
  + But beyond scope of this class
  + Combination of several files in [github folder][ref11]
  + Slightly obsolete explanation on [my blog][ref12]
  + [More current explanation][ref13] on using quarto and reveal.js
 
[ref11]: https://github.com/pmean/classes/tree/master/introduction-to-r/01/src
[ref12]: http://blog.pmean.com/powerpoint-with-r-markdown/
[ref13]: https://quarto.org/docs/presentations/revealjs/

  
::: notes

Okay. Let's get started.

Before I talk about the histormy of R, let me menion one housekeeping item.

This presentation was developed using R. The process is not very complicated, but it is beyond the scope of this class. 

I do want to note that I have switched recently from doing presentations using Powerpoint to presentations using reveal.js. I really like reveal.js, for a whole host of reasons that are hard to explain. The only difference that you might notice is that the presentations using reveal.js are html files. That means that you open them up using a web browser rather than Powerpoint.

If you are curious, you can look at the code that I used to develop this
PowerPoint presentation. It's all on my github site.

But don't feel obligated to look at it. You will not be responsible for any of this in an introductory class.

It may seem a bit weird to have an R program that creates a presentation that talks about a different R program, but it works well for me.

:::

## History of R

This portion of the talk will be found in the file [history-of-r.pptx][ref14].

[ref14]: https://github.com/pmean/classes/blob/master/general/history-of-r.pptx
