---
title: "See bottom of file for title"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "History of R"
  topic_02: "Installing R"
  topic_03: "Objects in R"
  topic_04: "Anatomy of a small R program"
  topic_05: "Live demonstration"
  topic_06: "Good programming practices"
  topic_07: "Your programming assignment"
editor: source
execute: 
  echo: true
---

## Special note

+ This slide show was created using R.
  + Not complicated 
  + But beyond scope of this class
  + Combination of several files in [github folder][ref01]
  + Slightly obsolte explanation on [my blog][ref02]
  + [More current explanation][ref03] on using quarto and reveal.js
  
::: notes

Okay. Let's get started.

If you are viewing this presentation, I need to point out that it was developed using R. The process is not very complicated, but it is beyond the scope of this class. 

I do want to note that I have switched recently from doing presentations using Powerpoint to presentations using reveal.js. I really like reveal.js, for a whole host of reasons that are hard to explain. The only difference that you might notice is that the presentations using reveal.js are html files. That means that you open them up using a web browser rather than Powerpoint.

If you are curious, you can look at the code that I used to develop this
PowerPoint presentation. It's all on my github site.

But don't feel obligated to look at it. You will not be responsible for any of this in an introductory class.

It may seem a bit weird to have an R program that creates a presentation that talks about a different R program, but it works well for me.

:::



## Topics to be covered

```{r}
# A small section of R code to kick start the params.
```

-   What you will learn
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`

{{< include _r-01-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

{{< include _r-01-02.qmd >}}

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`

{{< include _r-01-03.qmd >}}

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`

{{< include _r-01-04.qmd >}}

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`

{{< include _r-01-05.qmd >}}

## Break #5

-   What you have learned
    -   `r params$topic_05`
-   What's coming next
    -   `r params$topic_06`

{{< include _r-01-06.qmd >}}

## Break #6

-   What you have learned
    -   `r params$topic_06`
-   What's coming next
    -   `r params$topic_07`

{{< include _r-01-07.qmd >}}

## Summary

-   What you have learned
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`

[ref01]: https://github.com/pmean/classes/tree/master/introduction-to-r/01/src
[ref02]: http://blog.pmean.com/powerpoint-with-r-markdown/
[ref03]: https://quarto.org/docs/presentations/revealjs/

<!---
      You have to put the title down 
      here to override the titles of
      all the include files.
--->

---
title: "MEDB 5505, Module01"
date: 2025-01-23
---