---
title: "See bottom of file for title"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "01 Linear regresion, analysis of variance"
  topic_02: "02 Linear regression with multiple independent variables"
  topic_03: "03 Analysis of covariance"
  topic_04: "04 Multi-factor analysis of variance"
  topic_05: "05 Dimension reduction"
  topic_06: "06 Logistic regression"
  topic_07: "07 Diagnostic tests"
  topic_08: "08 Survival analysis"
  topic_09: "09 Meta-analysis"
  topic_10: "10 Dark side of data science"
  topic_11: "11 Hierarchical models"
  topic_12: "12 Longitudinal data"
  topic_13: "13 Bayesian statistics"
editor: source
---

## Topics to be covered, 1 of 2

```{r}
# Preliminaries, if needed

# Keep this chunk, even if no code, so that
# params is populated from the yaml header.

# To print speaker notes, add
#   ?print-pdf&showNotes=separate-page 
#   to the end of the URL. Then open the
#   print dialog box (ctrl-P) and choose
#   Save as PDF for the printer. Other 
#   options, like Microsoft Print to PDF
#   do not seem to work.
```

-   What you will learn
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`

## Topics to be covered, 2 of 2

-   What you will learn
    -   `r params$topic_08`
    -   `r params$topic_09`
    -   `r params$topic_10`
    -   `r params$topic_11`
    -   `r params$topic_12`
    -   `r params$topic_13`

{{< include _b2-14-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

{{< include _b2-14-02.qmd >}}

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`
    
{{< include _b2-14-03.qmd >}}

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`
    
{{< include _b2-14-04.qmd >}}

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`

{{< include _b2-14-05.qmd >}}

## Break #5

-   What you have learned
    -   `r params$topic_05`
-   What's coming next
    -   `r params$topic_06`

{{< include _b2-14-06.qmd >}}

## Break #6

-   What you have learned
    -   `r params$topic_06`
-   What's coming next
    -   `r params$topic_07`

{{< include _b2-14-07.qmd >}}

## Break #7

-   What you have learned
    -   `r params$topic_07`
-   What's coming next
    -   `r params$topic_08`

{{< include _b2-14-08.qmd >}}

## Break #8

-   What you have learned
    -   `r params$topic_08`
-   What's coming next
    -   `r params$topic_09`

{{< include _b2-14-09.qmd >}}

## Break #9

-   What you have learned
    -   `r params$topic_09`
-   What's coming next
    -   `r params$topic_10`

{{< include _b2-14-10.qmd >}}

## Break #10

-   What you have learned
    -   `r params$topic_10`
-   What's coming next
    -   `r params$topic_11`

{{< include _b2-14-11.qmd >}}

## Break #11

-   What you have learned
    -   `r params$topic_11`
-   What's coming next
    -   `r params$topic_12`

{{< include _b2-14-12.qmd >}}

## Break #12

-   What you have learned
    -   `r params$topic_12`
-   What's coming next
    -   `r params$topic_13`

{{< include _b2-14-13.qmd >}}

## Summary, 1 of 2

-   What you have learned
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`

## Summary, 2 of 2

-   What you have learned
    -   `r params$topic_08`
    -   `r params$topic_09`
    -   `r params$topic_10`
    -   `r params$topic_11`
    -   `r params$topic_12`
    -   `r params$topic_13`

<!---
      You have to put the title down 
      here to override the titles of
      all the include files.
--->

---
title: "MEDB 5502, Module 14, review"
---