---
title: "03-00, Resources needed for module 03 slides"
format: 
  html:
    embed-resources: true
editor: source
---

## Preliminaries

```{r}
#| label: setup
#| message: false
#| warning: false

library(tidyverse)
```

## Create grab functions

```{r}
#| label: grab

grab_entire_file <- function(fn) {
  tx <- read_lines(fn)
  paste0(c("```", tx, "```"), collapse="\n")
}

grab_code_segment <- function(fn, lab) {
  tx <- read_lines(fn)
  n_lines <- length(tx)
  start <- which(str_detect(tx, fixed(lab)))
  if (length(start) == 0) return("String not found")
  for (i in start:n_lines) {
    if (str_detect(tx[i], "```")) break
  }
  stop <- i
  paste0(c("```", tx[(start+2):stop]), collapse="\n")
}
```

## Create segments

```{r}
#| label: create-segments

simple_comma <- grab_entire_file("../data/simple.csv")
cat(simple_comma)

read_comma <- grab_code_segment(
  "simon-5505-03-demo-02.qmd", 
  "#| label: read-comma")
cat(read_comma)

simple_tab <- grab_entire_file("../data/simple.tsv")
cat(simple_tab)

read_tab <- grab_code_segment(
  "simon-5505-03-demo-03.qmd", 
  "#| label: read-tab")
cat(read_tab)

simple_tilde <- grab_entire_file("../data/tilde.txt")
cat(simple_tilde)

read_tilde <- grab_code_segment(
  "simon-5505-03-demo-04.qmd", 
  "#| label: read-tilde")
cat(read_tilde)

simple_fixed <- grab_entire_file("../data/fixed.txt")
cat(simple_fixed)

read_fixed <- grab_code_segment(
  "simon-5505-03-demo-05.qmd", 
  "# label: read-fixed")
cat(read_fixed)

peek_binary <- grab_code_segment(
  "simon-5505-03-demo-06.qmd", 
  "# label: peek-binary")
cat(peek_binary)

read_binary <- grab_code_segment(
  "simon-5505-03-demo-06.qmd", 
  "# label: read-binary")
cat(read_binary)

peek_barbershop <- grab_code_segment(
  "simon-5505-03-demo-06.qmd", 
  "# label: peek-barbershop")
cat(peek_barbershop)

read_barbershop <- grab_code_segment(
  "simon-5505-03-demo-06.qmd", 
  "# label: read-barbershop")
cat(read_barbershop)

peek_airport <- grab_code_segment(
  "simon-5505-03-demo-06.qmd", 
  "# label: peek-airport")
cat(peek_binary)

define_airport <- grab_code_segment(
  "simon-5505-03-demo-06.qmd", 
  "# label: define-airport")
cat(define_binary)

read_airport <- grab_code_segment(
  "simon-5505-03-demo-06.qmd", 
  "# label: read-airport")
cat(read_binary)

```

## Save everything important

```{r save}
save(
  simple_comma,
  read_comma,
  simple_tab,
  read_tab,
  simple_tilde,
  read_tilde,
  simple_fixed,
  read_fixed,
	file="../data/module03.RData")
```
