---
title: "Defining Clinical Research Methodology"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Learning objectives

+ To describe the variety of research that can be conducted while doing clinical research.

+ To describe what is needed in order to identify and define a research question that could be the basis for a research project.

::: notes
Here's what I will try to cover today
:::

## What is research?

* " systematic investigation, including research development, testing, and evaluation, designed to develop or contribute to generalizable knowledge"

  + [45 CFR 46.102](https://www.hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46/index.html)

* "Disciplined method" or "disciplined inquiry"

  + "dispassionate search for truth"
  
  + not dependent on surface plausibility or the status of the author.
  
  + [Gliner, Morgan, Leech. Research Methods in Applied Settings](https://books.google.com/books/about/Research_Methods_in_Applied_Settings.html?id=R23ADAAAQBAJ).
  

::: notes

Let's define the three words "clinical research methodology." Start with "research." I like the federal government's definition. This comes from the Code of Federal Regulations. Basically 45 CFR 46 is the section of the Code of Federal Regulations that set up rules and regulations for ethical conduct of research.

The key words in this definition are "generalizable knowledge." If you don't hope to extrapolate beyond the range of the data you collect, it isn't research.

There certain types of studies I like to call "warehouse studies," which is analogous to trying to find out what is in a certain storage area. Let me give an example from the time I was at Children's Mercy. They had a complaint about overbilling. In fairness to Children's Mercy that's a difficult topic. Quite honestly finding the appropriate level billing is difficult.

There were tens of thousands of records that they had to audit they didn't want to audit everything. Instead, we created a random sample of the records. The purpose of random samples NOT to generalize to other institutions. The whole idea was to try to find out how much Children's Mercy overcharged, so we could properly refund the overcharges.

This idea of generalizable knowledge is probably the dividing line between the quality improvement studies and research studies and this is very complicated. I will talk more about the later. We have a whole week dedicated to quality improvement studies. 

Gliner, Morgan, and Leech emphasize research as a disciplined method. They emphasize a dispassionate search for truth and independence from preconceived notions. A true researcher should be equally happy if they find that their hypothesis is right or wrong.

Even though internally there may be some level of disappointment, you are happy for your patients. You're interested not in burnishing your career. You're interested in finding the truth. So a good researcher rejoices whenever their research hypotheses is disproven because that's progress. You know more about what and what not to do for your patients. Negative trials are progress just as much as positive trial. I'm sure I'll talk more about that later. If you have a dispassionate search for the truth, finding out that a certain medication or certain therapy that you think really works did not work is in the best interest of your patients. 

Both definitions are good, but I like the government definition for its simplicity.

:::
 
## What is clinical? What is methodology?

* Clinical: "concerned with or based on actual observation and treatment of disease in patients rather than experimentation or theory."

  + [Dictionary.com](https://www.dictionary.com/browse/clinical)

* Methodology: "a body of methods, rules, and postulates employed by a discipline : a particular procedure or set of procedures"

  + [Merriam-Webster dictionary](https://www.merriam-webster.com/dictionary/methodology)

::: notes

The classic dictionary definitions for "clinical" and "methodology" work just fine. "Clinical" places the emphasis on patients and methodology is a body of rules.

Now some of you may be interested in non-clinical research, such as animal studies or computer simulations. These types of research will not be covered explicitly in this course, but there is enough commonality that you can still learn a lot of things that will help you in your research career. This also means that all of my examples will be oriented to medicine. There are people who come from outside of the medical field who take this class and they still a lot that can be gotten out of this class. Maybe 75% or more of the content is still relevant, but you just have to live with the fact that all the examples I talked about will be medical examples.

So if you're in this class and you're not a clinician, that's fine. If you animal studies, that's fine. If you do marketing research that's fine.

:::

## Research "flavors"

+ Many different nouns, same basic concept
  + Research aim
  + Research approach
  + Research goal
  + Research hypothesis
  + Research question
  + Research topic
  
::: notes

I just added this slide because I've always had trouble with this. I ask people what you are researching and I don't know what proper noun is. is it a research aim, research approach, research goal, research hypothesis, research question or research topic. There are slight and subtle differences among these terms, but I use them more or less interchangeably.

A research aim is a highly focused aspect of the research protocol or research grant. It tends to have a very narrow focus.

A research approach is really talking about the methods that you going to use.

A research goal is larger in scope than a research aim.

A research hypothesis is a term that I use more often than anything, but quite honestly a lot of research does not have a hypothesis. We need to get past that belief that if you don't have a hypothesis, you don't have research. A research hypothesis is something you postulated based on your understanding of the theory of medicine that you want to prove or disprove by collecting data. 

Research hypotheses tend to be black and white and I think sometimes it's good to think in black-and-white terms. Sometimes, though, trying to choose between only two alternatives is not a good approach to research

I need to warn you about this. If I ask you what you research hypothesis and you have a research questions, don't go all huffy on me. I use these interchangeably. I shouldn't but I do. I'll be honest: I am usually not sloppy with terminology. I am usually very precise with my words but this is one exception.

A research question is a term often used when a research study does not have a hypothesis. Here's a research question. How do children who have siblings with the chronic disease cope. The child that has a chronic disease get a lot more attention, has a lot of crises that can provoke fear and anxiety in the family, and so forth. There's no hypothesis here at all. There's no this mean is bigger than that mean, no this proportion is bigger than that proportion.

Finally a research topic is generally very broad and general.

I hope I got all those distinctions right. I may be wrong on some of the details because I do not fuss about the subtle dstinctions in these terms.

:::

## Elements of a research hypothesis

+ PICO
  + P = patient population
  + I = intervention (or exposure)
  + C = control or comparison group
  + O = outcome
+ PICOTS
  + T = time frame
  + S = setting
  
::: notes

To try to characterize research, especially research that includes a hypothesis, I look for four elements, P, I, C, and O. This comes from evidence-based medicine, the step where you ask an answerable question. In order to do a good job with evidence-based medicine, you first have to pose a question in a way that can be answered by reviewing the literature, reviewing the evidence. Okay, so the experts in evidence based medicine came up with this acronym, PICO. You don't always apply this too literally, but find that it helps.

P is the patient population: who you studied. Are you studying children, or studying the elderly. Are you studying people who present with the neck fracture? Sometimes it is not people. Sometimes, you are you studying the houses that people live in, because you are interested in environmental hazards like lead paint in the home.

I is the intervention. An intervention is when you when you change something. You try to physically intervene to mitigate the problem. You give a drug or offer a therapy. Sometimes I use the word exposure. Exposure is something that your patients endure. It's not something that you provide hoping for a cure. Second hand smoke is an exposure. Non-ionizing radiation is an exposure. Interventions are sometimes bad, but the intention is what matter. An intervention is intended to make things better, while an exposure is something that might make things worse.

C is the control or comparison group. Research hypothesis, almost always, involves some sort of comparison groups. Typically it is a control group. The control group either does not get the intervention, or they get part of the intervention only, or they get an alternate intervention.

There certain cases where you don't have a comparison group. If you are trying to assess the quality of a diagnostic test, it gets a bit harder because everyone gets the diagnostic test. You can try to force this by defining a C, but this is usually not worth the effort.

There's an extension of this acronym, PICOTS. T specifies the time frame and S specifies the setting. These are important differences between a study based in a tertiary care center rather than in a first-line clinic. I sometimes look for the T and the S, but I always look for the first four, P-I-C-O.

:::

## Where do research ideas come from?

Ronan Conroy has an excellent summary.

* Exploring your environment.

* Don't focus prematurely on a single idea.

* Extending the ideas of others.

* Getting a research idea by reading papers.

My theory

* Irritation

::: notes

There's an excellent summary of how to come up with a research idea that I was asked to host on my website. It was collated from various postings on an email discussion group by Ronan Conroy.

I have lost touch with Ronan Conroy, but he and I use to correspond by Internet a lot. He's a really smart guy in Ireland who wrote a very nice summary of where do research ideas come from. He pulled a bunch of ideas from the discussion board that he was on and he wrote it up very nicely. He came to me and asked if I could post his summary on my website. I was happy to do this, because it was so well written.

His outline has four main topics. I don't want to go into too much detail, but the first suggestion is to explore your environment. Look around. Sometimes stuff is sitting right under your nose. Now there are two types of students in this class. There are students who are already deeply involved in clinical responsibilities. They may be a medical resident or fellow, they may actually have the terminal medical degree, and they want to get more involved in research. These students usually are swimming in ideas because there's all this they see every day in the clinic. 

Now I have to say I'm not good at this because I don't do clinical work. I don't see patients. I'm looking from the outside. Sometimes that's a big advantage. I can be more objective about problems, I can look at the problem more abstractly. I can bring in solutions from other disciplines. So it's good to be an outsider to some extent. But if you're like me and your background is more mathematical or more computational, you may have trouble coming up with a good research idea. You don't live in the clinic the way other students do. See if you can talk to someone who has that clinical experience and ask them for help picking a good research topic.

The other thing is to avoid focusing prematurely on a single idea. You need that branch out and not have tunnel vision.

A third approach is to extend the ideas of others. William Shakespeare was a great, great writer, wrote some wonderful plays, but he stole most of these plays from someone else. He just wrote them so much better than the original sources that that's why we remember his name today and not any of those other people.

Extending the idea of others is not plagiarism. It's not stealing. It's part of research. So, for example, there may be a a fair amount known already about how to get people to lose weight when they are physically handicapped and do not have the ability to exercise. Even so, there is always a way to improve one the currently best available interventions.

If we are talking about treatment of cancer, there are always ways we can improve the treatments. For example, you might work to reduce the side effects of some these very harsh drugs. 

If you are a beginning resarchers, the last thing you want to try to do is come up with something that's totally de novo, something that's brand-new, something that no one else has ever thought of. Few of us, and I put myself in this category, are so smart that they can develop something brand-new is never been thought of before.

The last suggesiton is closely related. Read other people's research papers. These papers have a literature review, a methods section, a  results section, and a discussion section. Look at that discussion and look at where they say "options for further research." These people are giving you free advice.

Okay, now my theory about research is a lot simpler why people do research. It's the irritation principal. They see something's wrong and it just bothers them. There are two types of wrong. There's I'm doing something right now that I know I could be doing better okay. There is also I'm doing it right, but no one else is. Either way, there's a sense of irritation. It's that they have an itch that they just have to scratch. There is something that needs to be fixed and I won't feel right until I try to fix it. That's where I think for a lot of research ideas come from. 

All these ideas are all good, but let me emphasize the importance of reading. Almost every research paper includes suggestions for further research in their discussion section. This is free advice from researchers who have proved that they can get their work published.

:::

## Uses of clinical research

* Practical application.

* Theory development.

* Development of research tools.

* Professional development.

::: notes

Why do we do clinical research? Let's let's be honest about this is several reasons. It's not just the practical application--learning about something that can improve the care you provide to your patients. 
Sometimes research is done for theory development--understanding why and how diseases progress. 

You can also conduct research to develop new tools to improve the research process (this is an area I am very interested in). 

You can also conduct research for your own professional development. Nothing makes you a better consumer of other people's research than doing a bit of research yourself.

It's important to understand your motivations for doing research, because different motivations result in different priorities. In particular, the pedagogical benefits of conducting a research study will often drive a thesis committee to encourage approaches that broaden a student's understanding of the research process, even though a different approach might be better.

Don't get me wrong. Most of the time you can improve your knowledge and benefit your patients at the same time. 

:::
