---
title: "Defining Clinical Research Methodology"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Learning objectives

+ To describe the variety of research that can be conducted while doing clinical research.

+ To describe what is needed in order to identify and define a research question that could be the basis for a research project.

::: notes
Here's what I will try to cover today
:::

## What is research?

* " systematic investigation, including research development, testing, and evaluation, designed to develop or contribute to generalizable knowledge"

  + [45 CFR 46.102](https://www.hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46/index.html)

* "Disciplined method" or "disciplined inquiry"

  + "dispassionate search for truth"
  
  + not dependent on surface plausibility or the status of the author.
  
  + [Gliner, Morgan, Leech. Research Methods in Applied Settings](https://books.google.com/books/about/Research_Methods_in_Applied_Settings.html?id=R23ADAAAQBAJ).
  

::: notes

Let's define the three words "clinical research methodology." Start with "research." I like the federal government's definition. This comes from the Code of Federal Regulations. Basically 45 CFR 46 is the section of the Code of Federal Regulations that set up rules and regulations for ethical conduct of research.

The key words in this definition are "generalizable knowledge." If you don't hope to extrapolate beyond the range of the data you collect, it isn't research.

There certain types of studies I like to call "warehouse studies," which is analogous to trying to find out what is in a certain storage area. Let me give an example from the time I was at Children's Mercy. They had a complaint about overbilling. In fairness to Children's Mercy that's a difficult topic. Quite honestly finding the appropriate level billing is difficult.

There were tens of thousands of records that they had to audit they didn't want to audit everything. Instead, we created a random sample of the records. The purpose of random samples NOT to generalize to other institutions. The whole idea was to try to find out how much Children's Mercy overcharged, so we could properly refund the overcharges.

This idea of generalizable knowledge is probably the dividing line between the quality improvement studies and research studies and this is very complicated. I will talk more about the later. We have a whole week dedicated to quality improvement studies. 

Gliner, Morgan, and Leech emphasize research as a disciplined method. They emphasize a dispassionate search for truth and independence from preconceived notions. A true researcher should be equally happy if they find that their hypothesis is right or wrong.

Even though internally there may be some level of disappointment, you are happy for your patients. You're interested not in burnishing your career. You're interested in finding the truth. So a good researcher rejoices whenever their research hypotheses is disproven because that's progress. You know more about what and what not to do for your patients. Negative trials are progress just as much as positive trial. I'm sure I'll talk more about that later. If you have a dispassionate search for the truth, finding out that a certain medication or certain therapy that you think really works did not work is in the best interest of your patients. 

Both definitions are good, but I like the government definition for its simplicity.

:::
 
## What is clinical? What is methodology?

* Clinical: "concerned with or based on actual observation and treatment of disease in patients rather than experimentation or theory."

  + [Dictionary.com](https://www.dictionary.com/browse/clinical)

* Methodology: "a body of methods, rules, and postulates employed by a discipline : a particular procedure or set of procedures"

  + [Merriam-Webster dictionary](https://www.merriam-webster.com/dictionary/methodology)

::: notes

The classic dictionary definitions for "clinical" and "methodology" work just fine. "Clinical" places the emphasis on patients and methodology is a body of rules.

Now some of you may be interested in non-clinical research, such as animal studies or computer simulations. These types of research will not be covered explicitly in this course, but there is enough commonality that you can still learn a lot of things that will help you in your research career. This also means that all of my examples will be oriented to medicine. There are people who come from outside of the medical field who take this class and they still a lot that can be gotten out of this class. Maybe 75% or more of the content is still relevant, but you just have to live with the fact that all the examples I talked about will be medical examples.

So if you're in this class and you're not a clinician, that's fine. If you animal studies, that's fine. If you do marketing research that's fine.

:::

## Research "flavors"

+ Many different nouns, same basic concept
  + Research aim
  + Research approach
  + Research goal
  + Research hypothesis
  + Research question
  + Research topic
  
::: notes

I just added this slide because I've always had trouble with this. I ask people what you are researching and I don't know what proper noun is. is it a research aim, research approach, research goal, research hypothesis, research question or research topic. There are slight and subtle differences among these terms, but I use them more or less interchangeably.

A research aim is a highly focused aspect of the research protocol or research grant. It tends to have a very narrow focus.

A research approach is really talking about the methods that you going to use.

A research goal is larger in scope than a research aim.

A research hypothesis is a term that I use more often than anything, but quite honestly a lot of research does not have a hypothesis. We need to get past that belief that if you don't have a hypothesis, you don't have research. A research hypothesis is something you postulated based on your understanding of the theory of medicine that you want to prove or disprove by collecting data. 

Research hypotheses tend to be black and white and I think sometimes it's good to think in black-and-white terms. Sometimes, though, trying to choose between only two alternatives is not a good approach to research

I need to warn you about this. If I ask you what you research hypothesis and you have a research questions, don't go all huffy on me. I use these interchangeably. I shouldn't but I do. I'll be honest: I am usually not sloppy with terminology. I am usually very precise with my words but this is one exception.

A research question is a term often used when a research study does not have a hypothesis. Here's a research question. How do children who have siblings with the chronic disease cope. The child that has a chronic disease get a lot more attention, has a lot of crises that can provoke fear and anxiety in the family, and so forth. There's no hypothesis here at all. There's no this mean is bigger than that mean, no this proportion is bigger than that proportion.

Finally a research topic is generally very broad and general.

I hope I got all those distinctions right. I may be wrong on some of the details because I do not fuss about the subtle dstinctions in these terms.

:::

