---
title: "04-00, Resources needed for module 04 slides"
format: 
  html:
    embed-resources: true
editor: source
---

```{r setup-0}
#| message: false
#| warning: false

library(tidyverse)
library(yaml)
```

## Data dictionary

```{r}
#| label: yaml
#| message: false
#| warning: false

library(yaml)

f1 <- "https://raw.githubusercontent.com/"
f2 <- "pmean/data/refs/heads/main/files/"
f3 <- "titanic.yaml"
titanic_dictionary <- read_yaml(paste0(f1, f2, f3))
```

`r titanic_dictionary$description`

## Create grab functions

```{r}
#| label: grab

grab_entire_file <- function(fn, max_lines=10) {
  tx <- read_lines(fn)
  if (length(tx) > max_lines) tx <- tx[1:max_lines]
  paste0(c("```", tx, "```"), collapse="\n")
}

grab_code_segment <- function(fn, lab) {
  tx <- read_lines(fn)
  n_lines <- length(tx)
  start <- which(str_detect(tx, fixed(lab)))
  if (length(start) == 0) return("String not found")
  for (i in start:n_lines) {
    if (str_detect(tx[i], "```")) break
  }
  stop <- i
  paste0(c("```", tx[(start+2):stop]), collapse="\n")
}
```

## Create segments

```{r}
#| label: create-segments

titanic_data <- grab_entire_file("../data/titanic.csv")
cat(titanic_data)

titanic_read <- grab_code_segment(
  "simon-5505-04-demo-01.qmd", 
  "#| label: titanic-read")
cat(titanic_read)

titanic_tail <- grab_code_segment(
  "simon-5505-04-demo-01.qmd", 
  "#| label: titanic-tail")
cat(titanic_tail)

```

```{r save}
save(
	titanic_dictionary,
	titanic_data,
	titanic_read,
	titanic_tail,
	file="../data/module04.RData")
```
