---
title: "What is a quality improvement?"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Objectives

1. To contrast the features of a quality improvement study with a research study

2. To describe the various quasi-experimental approaches

::: notes
Here are the objectives for this week. I want to introduce some new material on quality improvement (QI) studies and this is the best place to put it. Although QI and medical research share many features, you need to appreciate some important differences between the two approaches. Many QI studies use quasi-experimental approaches and we'll discuss a few of the more common ones.
:::

## Different names for the same thing {.smaller}

-   Agile
-   Continuous Quality Improvement (CQI)
-   Kaizen
-   Lean
-   Quality Control (QC)
-   Six Sigma
-   Statistical Process Control (SPC)
-   Total Quality Management (TQM)
-   Different from Quality Assurance

::: notes
Some of the material discussed on this page was taken from

https://www.hrsa.gov/sites/default/files/quality/toolbox/508pdfs/qualityimprovement.pdf

Quality Improvement (QI) is a broad area and has appeared under various labels like six sigma and total quality management. There are some subtle differences among these approaches. Lean places a strong emphasis on waste reduction, while TQM paces more emphasis on management. In general, different people like different terminology, and they will argue strenuously that their acronym is the superior acronym, and that all other acronyms are inferior, usually because, but they are not important from your perspective.

It is quite different from Quality Assurance, which has more of an audit function.

QI is a systematic approach to changing how a health care organization works with the goal of providing better health care delivery. The approach has been tested in the fields of business and engineering over the 100 years ago, and the health care systems started adopting these approaches starting about 25 years ago.
:::

## Development of quality improvement methods

-   Historical roots
    -   Walter Shewhart (1920s, General Electric)
    -   W. Edwards Deming (1950s, Japan)
    -   Brent James (1990s, Intermountain Health Care)

::: notes
The historical roots of QI can be found in the contributions of three statisticians, Walter Shewhart, W. Edwards Deming, and Brent James. I get to brag a bit here, because the Statistics profession is one that is largely anonymous to the outside world, but Shewhart and Deming are two exceptions.

Walter Shewhart worked at General Electric in the 1920s and developed the statistical control chart, and described the concept of common cause and special cause variation. 

W. Edwards Deming was a statistician assigned to post-war Japan in the 1950s to work on their census, but ended up helping out with the rebuilding of industries in that country as well. He described a management philosophy that emphasized the involvement of everyone in an organization in the quality improvement process. 

Brent James is the chief quality officer at Intermountain Healthcare and has spoken about the culture change needed in medicine to improve quality and has trained thousands of health care professionals on how to conduct clinical practice improvement projects.
:::

## Process underlying quality improvement

-   Systematic approach
    -   Commitment to teams
    -   Organization-wide support
    -   Passion for measurement

::: notes
The QI process makes a strong commitment to teams and emphasizes the importance of broad representation on the team and careful elicitation of viewpoints from every perspective. While it is possible to run a QI team in a small corner of an organization, the QI process can only function well with organization-wide support, especially support from upper management. The QI process has a strong commitment to measurement, as measurement is the only way to evaluate the success or failure of changes made by the QI process.
:::

## Quality improvement versus research

-   Differences from research
    -   Systems approach
    -   Little or no attention to generalizability
    -   Continuous and cyclical process
    -   Major reliance on quasi-experimental studies

::: notes
There is substantial overlap between QI and health care research, but you should be aware of several important differences. QI takes a systems approach to solving problems. Some research takes a systems approach as well, but it's not really a research requirement. QI pays little or no attention to generalizability. The focus of QI is on your particular organization, and attempts to generalize to other organizations is not a priority. The QI process is not a single step but a continuous effort. This effort is usually represented by the PDCA or PDSA process (Plan, Do, Check/Study, and Act) and each time you reach the end of a PDCA cycle, you start over again with a new plan.

The final distinction and the reason I am talking about the QI process in this class it that QI relies heavily (but not exclusively) on quasi-experimental studies.
:::
