---
title: "Cross-sectional designs"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## What is a cross-sectional design?

-   Single group
    -   No selection by exposure
    -   No selection by outcome
-   Can be prospective or retrospective

::: notes

In a cross-sectional design, you're sample is a single group of patients. You don't go hunting for controls among unexposed patients. You don't go hunting for controls among the non-cases. It's the ultimate in one stop shopping.

You might have trouble sometimes determining the difference between a cross-sectional study and a cohort study. Did you select a single group, which naturally divided itself into an exposed cohort and un-exposed controls?  Or did you select an exposed cohort and then separately find an unexposed set of controls?

Cross-sectional designs can be prospective or retrospective.

:::

## Disadvantages of cross-sectional designs

-   Disadvantages
    -   Confusion about temporal ordering
    -   Selection bias, confounding

::: notes

It was a physicist, John Archibald Cox, who notes that "time is nature's way of keeping everything from happening all at once." True enough, but in a cross sectional design, you collect data all at once about exposures and outcomes and sometimes you can get confused about what happened first.

There's a bad joke about a statistician who examined fire department records and concluded that the more fire trucks you send to the scene of a fire, the more damage that they cause.

In general, an exposure has to occur before the outcome in order to conclude that it caused the outcome. And this might be easy to miss in a cross-sectional design.

Like the cohort design, the cross-sectional design has problems with selection bias and confounding.

:::

## Advantages of cross-sectional designs

-   Advantages
    -   Examine multiple risk factors, multiple outcomes
    -   Realistic setting

::: notes

There are several advantages to a cross-sectional design.

Because you are not selecting a single exposure or a single outcome, you have a lot of flexibility to explore multiple exposures against multiple outcomes.

The cross-sectional design is also the most natural and intuitive setting for a research study. You can envision a sampling process that produces this study and in many settings, this sampling produces a realistic picture of the health care process. More realistic than the case control design certainly, and more realistic, possibly, than the cohort designs where the two groups have an artificial distinction between them. You could even argue that a cross-sectional design is more natural than a randomized control trial, because volunteer bias and the extra attention that are part and parcel of a randomized trial make it, at times, a poor representation of how health care is delivered.

:::

