---
title: "02-02, Computing counts and percentages using R"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
execute:
  echo: false
  message: false
  warning: false
---

## Data dictionary for legionnaires-disease, 1

```{r data0}
library(glue)
library(stringr)
library(yaml)
f1 <- "https://raw.githubusercontent.com/pmean"
f2 <- "data/main/files/legionnaires-disease.yaml"
dd <- read_yaml(glue("{f1}/{f2}"))
dd <- read_lines(glue("{f1}/{f2}"))
h <- str_which(dd, "^$")
chunk_beg <- c(1, h-1)
chunk_end <- c(h, length(dd))
}

```{r data1}
cat(dd[chunk_beg[1]:chunk_end[4]])
```

## Data dictionary for legionnaires-disease, 2

```{r data5}
cat(dd[chunk_beg[5]:chunk_end[8]])
```

## Data dictionary for legionnaires-disease, 3

```{r data9}
cat(dd[chunk_beg[9]:chunk_end[11]])
```



```{r data2}
part2 <- c(
  "description",
  "download_url")
for (i in part2) {
  cat(as.yaml(dd[i]))
	cat("\n")
}
```

## simon-5501-02-legionnaires.qmd, 1 of 5

```{r write1}
library(tidyverse)
fn <- "simon-5501-02-legionnaires.qmd"
template <- read_lines(file=fn)
h <- str_which(template, "##")
g <- h-1
template[1:g[1]] |>
	paste0(collapse="\n") |>
	cat()
```

:::notes
The first few lines are the documentation header
:::

## simon-5501-01-template.qmd, 2 of 5

```{r write2}
template[h[1]:g[2]] |>
	paste0(collapse="\n") |>
	cat()
```

## simon-5501-01-template.qmd, 3 of 5

```{r write3}
template[h[2]:g[3]] |>
	paste0(collapse="\n") |>
	cat()
```

## simon-5501-01-template.qmd, 4 of 5

```{r write4}
template[h[3]:g[4]] |>
	paste0(collapse="\n") |>
	cat()
```

## simon-5501-01-template.qmd, 5 of 5

```{r write5}
template[h[4]:length(template)] |>
	paste0(collapse="\n") |>
	cat()
```


