---
title: "Directions for 5501-02 programming assignment"
author: "Steve Simon"
format: 
  html:
    embed-resources: true
date: 2024-08-18
---

Before you start this assignment, download all the files listed on the
Canvas page for this programming assignment.

## Question #1

Calculate the counts and percentages for gender in the sharing dataset.
Interpret these values.

## Question #2

Calculate the counts and percentages for employment_status in the 
sharing dataset. Interpret these values.

## Quetion #3

Calculate the mean and standard deviation for the change in bacterial 
counts. Interpret these numbers.

## Question #4

Calculate the median, minimum, and maximum for the change in bacterial
counts. Is the median much different than the mean? Characterize the 
range as either wide or narrow.

## Your submission

-   Save the output in html format
-   Convert it to pdf format.
-   Make sure that the pdf file includes
    -   Your last name
    -   The number of this course
    -   The number of this module
-   Upload the file

## If it doesn't work

If your program has any errors or fails to produce the output that you
desire and you can't resolve the problem,  upload the program file 
along with the pdf file to help us figure out what went wrong. You 
will get a chance to resubmit the assignment if needed.

## File details

This file was created on 2024-08-27 and is placed in the public domain.