---
title: "Comments for MEDB 5502, Week 02"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "Three models for predicting a continuous outcome"
  topic_02: "Analysis of variance table"
  topic_03: "Variable selection"
  topic_04: "Stepwise regression"
  topic_05: "Residual analysis"
  topic_06: "Collinearity"
  topic_07: "Mediation"
editor: source
---

## Topics to be covered

```{r}
# Preliminaries, if needed

# Keep this chunk, even if no code, so that
# params is populated from the yaml header.

# To print speaker notes, add
#   ?print-pdf&showNotes=separate-page 
#   to the end of the URL. Then open the
#   print dialog box (ctrl-P) and choose
#   Save as PDF for the printer. Other 
#   options, like Microsoft Print to PDF
#   do not seem to work.

```

-   What you will learn
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`

{{< include _b2-02-01.qmd >}}

## Live demo #1, ANOVA and R-squared

Refer to the [demonstration program for module02][ref01].

[ref01]: https://github.com/pmean/classes/blob/master/biostats-2/02/src/simon-5502-02-demo.qmd

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

{{< include _b2-02-02.qmd >}}

## Live demo #2, ANOVA and R-squared

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`
    
{{< include _b2-02-03.qmd >}}

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`
    
{{< include _b2-02-04.qmd >}}

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`

{{< include _b2-02-05.qmd >}}

## Live demo #3, residual plots

## Break #5

-   What you have learned
    -   `r params$topic_05`
-   What's coming next
    -   `r params$topic_06`

{{< include _b2-02-06.qmd >}}

## Live demo #4, multicollinearity

## Break #6

-   What you have learned
    -   `r params$topic_06`
-   What's coming next
    -   `r params$topic_07`

{{< include _b2-02-07.qmd >}}

## Live demo #5, mediation

## Summary

-   What you have learned
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`

<!---
      You have to put the title down 
      here to override the titles of
      all the include files.
--->

---
title: "Comments for MEDB 5502, Week 02"
---