---
title: "See title at the bottom of this file"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "Secondary data analysis"
  topic_02: "Centers for Disease Control and Prevention"
  topic_03: "Bureau of the Census"
  topic_04: "Cohort designs"
  topic_05: "Case-control designs"
  topic_06: "Cross-sectional designs"
  topic_07: "Historical control designs"
  topic_08: "Establishing causation in an observational design"
  topic_09: "Qualitative data, phenomenology"
  topic_10: "Grounded theory"
  topic_11: "Ethnography"
  topic_12: "The case sudy"
  topic_13: "Narrative"
  topic_14: "Community-Based Participatory Research"
editor: source
---

## Topics to be covered {.smaller}

```{r}
# Preliminaries, if needed

# Keep this chunk, even if no code, so that
# params is populated from the yaml header.

# To print speaker notes, add
#   ?print-pdf&showNotes=separate-page 
#   to the end of the URL. Then open the
#   print dialog box (ctrl-P) and choose
#   Save as PDF for the printer. Other 
#   options, like Microsoft Print to PDF
#   do not seem to work.
```

:::: {.columns}

::: {.column width="50%"}

-   What you will learn, part 1
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`

:::

::: {.column width="50%"}

-   What you will learn, part 2
    -   `r params$topic_09`
    -   `r params$topic_10`
    -   `r params$topic_11`
    -   `r params$topic_12`
    -   `r params$topic_13`
    -   `r params$topic_14`

:::

::::

{{< include _crm-06-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

{{< include _crm-06-02.qmd >}}

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`
    
{{< include _crm-06-03.qmd >}}

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`
    
{{< include _crm-06-04.qmd >}}

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`

{{< include _crm-06-05.qmd >}}

## Break #5

-   What you have learned
    -   `r params$topic_05`
-   What's coming next
    -   `r params$topic_06`

{{< include _crm-06-06.qmd >}}

## Break #6

-   What you have learned
    -   `r params$topic_06`
-   What's coming next
    -   `r params$topic_07`

{{< include _crm-06-07.qmd >}}

## Break #7

-   What you have learned
    -   `r params$topic_07`
-   What's coming next
    -   `r params$topic_08`

{{< include _crm-06-08.qmd >}}

## Break #8

-   What you have learned
    -   `r params$topic_08`
-   What's coming next
    -   `r params$topic_09`

{{< include _crm-06-09.qmd >}}

## Break #9

-   What you have learned
    -   `r params$topic_09`
-   What's coming next
    -   `r params$topic_10`

{{< include _crm-06-10.qmd >}}

## Break #10

-   What you have learned
    -   `r params$topic_10`
-   What's coming next
    -   `r params$topic_11`

{{< include _crm-06-11.qmd >}}

## Break #11

-   What you have learned
    -   `r params$topic_11`
-   What's coming next
    -   `r params$topic_12`

{{< include _crm-06-12.qmd >}}

## Break #12

-   What you have learned
    -   `r params$topic_12`
-   What's coming next
    -   `r params$topic_13`

{{< include _crm-06-13.qmd >}}

## Break #13

-   What you have learned
    -   `r params$topic_13`
-   What's coming next
    -   `r params$topic_14`

{{< include _crm-06-14.qmd >}}

## Summary {.smaller}

:::: {.columns}

::: {.column width="50%"}

-   What you have learned, part 1
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`

:::

::: {.column width="50%"}

-   What you have learned, part 2
    -   `r params$topic_09`
    -   `r params$topic_10`
    -   `r params$topic_11`
    -   `r params$topic_12`
    -   `r params$topic_13`
    -   `r params$topic_14`

:::

::::

<!---
      You have to put the title down 
      here to override the titles of
      all the include files.
--->

---
title: "Comments for MEDB 5510, Week 06"
---