---
title: "Directions for 5501-01 programming assignment"
author: "Steve Simon"
format: 
  html:
    embed-resources: true
date: 2024-08-18
---

This code is placed in the public domain.

## Setup

-   Download the [template][tem]
    -   Store it in your src folder
-   Modify the file name
    -   Use your last name instead of "simon"
-   Modify the documentation header
    -   Add your name to the author field
    -   Optional: change the copyright statement
-   Download the [data file][dat]
    -   Store it in your data folder

[tem]: https://github.com/pmean/classes/blob/master/biostats-1/01/src/simon-5501-01-template.qmd
[dat]: https://github.com/pmean/datasets/blob/master/albuquerque-housing.csv
    
## Interpret the output

I provided an interpretation for mean
price. Provide a similar interpretation 
for the other three means. Be sure to

-   use a descriptive name
-   include the units of measurement, if appropriate
-   round to two or three significant digits
-   use comma separators for numbers 1,000 or larger

## Your submission

-   Save the output in html format
-   Convert it to pdf format.
-   Make sure that the pdf file includes
    -   Your last name
    -   The number of this course
    -   The number of this module
-   Upload the file

## If it doesn't work

If your program has any errors or fails
to produce the output that you desire 
and you can't resolve the problem, 
upload the program file along with the
pdf file to help us figure out what 
went wrong. You will get a chance to 
resubmit the assignment if needed.
