---
title: "Quantitative versus qualitative research"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## What is quantitative research

-   Quantitative research.
    -   Synonym(?): Positivistic.
    -   Highly structured, A priori specifications.
    -   Separates the researcher from the research.
    -   Data is easily represented as numbers
  
::: notes

Now this is where you book is often the deep end. They talk about qualitative research versus quantitative research but then they talk about qualitative data versus quantitative data and then they talk about qualitative analysis versus quantitative analysis. I believe these are pretty close to being the same thing. So I'm just going to call it quantitative research versus qualitative research.

I'm not an expert in philosophy, but there is a branch of philosophy called positivism. It closely related to something called empiricism.

Positivism is the belief that if you use a well-defined process, you or anyone else can arrive at what we considered truth.There a lot of people who are very strong proponents of positivism. They believe that there's a certain procedure that you can follow and if you follow it carefully, researcher bias is removed from the equation. Two researchers, even if one has different preconceived notions than the other will still arrive at the same conclusion.

The Food and Drug Administration (FDA) is probably the regulatory agency that's furthest along in this idea of positivism. They believe that a company that makes a million-dollar actually close to $1 billion investment in drug development can still produce truthful answers about the safety and efficacy of their drug or device, in spite of all of these economic incentives. The FDA puts a massive number of checks and controls in place, and require such careful specification and documentation of the process that they can insure that the company will provide an objective finding about whether their drug or device is safe and effective.

FDA is very close on the positivism side of things, but I'll be honest, it's really really hard to provide a process that's not contaminated or influenced by people's preconceived notions.

Empiricism is a belief that any questions of importance in science can be answered if you collect enough data. I love data. I'm a statistician. I would be in the wrong field if I didn't love data. But I'll be damned if I think the data is the be-all and end-all. Data itself has limitations.

How do we collect data? There's a physical process where you collect data, all right, but there's also a social process involved and the I strongly believe that how people view things will change how they ask questions in an interview, even if they're given a script. 

You need to think about this because of no one believes positivism to the last degree, but there's a philosophy called postpositivism which is what we know that there's going to be biases, but they can be largely removed to the point where we come up with a very close approximation to what is true.

Quantitative research is highly structured, where everything is specified, a priori, and if you deviate from those specifications you have to go to the IRB get an amendment and you have to describe that protocol change in your paper and it's a ding against you wake comes to critical appraisal.

It's good to have a well structured protocol. It's good to specify things a priori to the extent that you can, but I think some of this is naïve and there's a great quote by Stephen Senn that illustrates this. Stephe Senn is a statistician is done a lot of work with the pharmaceutical industry. So you think you be a positivist. But he said a medical biostatistician is the only one who doesn't believe in America because it wasn't in Christopher Columbus's original research plan.

So the point is that trying to specify everything a priori is naïve.

The goal here of quantitative research and positivism is to separate the researcher from the research.

Quantitative research works with data that can be easily represented as numbers. Now there isn't anything that can't be turned into a number if you work hard enough at it, but the process is clear, transparent, and obvious in quantitative research

:::

## What is Quantitative research versus qualitative research

-   Qualitative research.
    -   Synonyms(?): Constructivist, humanist.
    -   Covers five sub-areas: phenomological, grounded theory, ethnographic, case study, and narrative research.
    -   Open ended questions. Research guides and is guided by the research process.
    -   Data is open ended text--difficult to represent as numbers
    -   Measures perceptions, feelings, values
-   Postpositivism tries to reconcile quantitative and qualitative approaches.  

::: notes

The qualitative/constructivist approach to research rejects the idea of objective collection of data. Biases in the data collection process are inevitable because they are dependent on the paradigm or common way of thinking that researchers share. Rather than separate the researcher from the data collection once the protocol is writen, a qualitative approach inserts the researcher directly into the data collection and explicitly specifies the paradigm that should be used during the research process. The researcher influences the data collection and is simultaneously influenced by the data collection.

The act of collecting data is a social process. So, for example, the U.S. Census makes certain decisions about how they train their census workers where they send them and the instructions that they give to athem. So for example if a knock on the door and no one answers, then they Will try to get information about that house and the inhabitants from the next door neighbor.

That's a process that the census uses to develop something which is the number of people who live in a certain area. It's not an objective process is a process is decided based on certain social norms about what's acceptable and what's unacceptable.

Constructivism is controversial because it seems to imply that there is no reality, and that everyone constructs their own reality. That's not true. What ta constructivist believes is that the process in which we decide what's true and what's not true is determined by society and society has certain prejudices.

There's a great book called the The Mismeasure of Man. It's written by Stephen Jay Gould. Stephen Jay Gould is a famous biologist who did a lot of work with evolution and came up with some really startling changes to the theory of evolution. In the book, The Mismeasure of Man, he looked at how researchers measure intelligence to things like IQ tests and he claims that these measures are flawed because the process of developing an IQ is a social process. People decide what questions go on the IQ test, and what answers represent more intelligence or less intelligence and this is a social process. It is subject to social biases and in particular if the people involved in the development of intelligence testing have either overt or hidden biases, that can create a biased test.

There is also Joel Best, who wrote a book, Damned Lies and Statistics who argues that all statistics are social process and you need to understand the process by which these statistics are derived. That doesn't mean that you don't believe the statistics, but you have to first think carefully about how those numbers were created. So for example, there are Criminologists who creates statistics on crime rates. Frequently, these statistics come ultimately from the Police Department. The Police Department is going to provide information about how many crimes occurred where they occurred. The classify the types of crimes and the seriousness of those crimes. Police Departments have certain perspectives on how they want to be seen and this can consciously or unconsciously influence how they collect this data.

Now a constructivist does indeed believe that you cannot separate the researcher from the research. But that doesn't mean that you don't do research. What it means is that you understand that the researcher is influenced by the research and influences the research. In particular the researcher should look at the data collection process as it develops and change the process based on what they observe.

So the early data in a constructivist approach or qualitative approach influences how the later data is collected. Now this would be anathema to people who believe that you need to specify everything in advance.  But the  constructivist says that if you think that produces objective data you're being naïve. Instead, you should embrace the fact that researchers do influence the research and try to harniess this influence in a structured way.

So, for example, if you run a focus group, you decide what additional questions to ask based on how the earlier questions were answered. To me it seems obvious that you ought to do it that way. If you say I have a script and I'm going to stick with it no matter what, that strikes me as a very naïve approach to research.

Even so, there are times when you want to use a certain questionnaire and you don't want to deviate. So this idea quantitative is good and qualitative is bad or vice versa is wrong. I want to get you away from that narrow-mindedness. There are times when you want quantitative approach in their times and you want a qualitative approach. 

A defining characteristic of the qualitative/constructivist approach is the use of open ended questions that allow the participants to describe things from their own perspective.

There  are attempts to reconcile these two philosophies. Postpositivism (don't you love that word) recognizes that you can't totally remove the researcher from the data collection process but sees the quantitative philosophy as a way to minimize the unavoidable biases that all researchers have.

Quantitative data is data that is easily reduced to a number or category, while qualitative data is not so easily reduced. This is kind of a squishy definition because you can create categories (themes) from qualitative data, but it takes a lot of effort.

Why would you ever use qualitative data if it takes more effort? Qualitative data offers a richness that cannot often get captured by quantitative data.

The other important issue with respect to qualitative research are the five broad areas that encompass most qualitative research. I will talk in more detail about these categories later in the class, but let me mention that I don't like categories. Categories are valuable because when you say I'm doing phenomenological research, people understand what you doing. It's a shorthand that I think has values.

But if you look at the definitions of the various types of qualitative research. How different, for example, is a case study compared to a narrative review.

Qualitative research often uses open-ended questions and sometimes the questions that you ask change depending on what the answers to previous questions were. 

The data that you collect in qualitative research is text--words and it's often difficult to provide a good representation of words in numbers. Qualitative researchers do this and they do it well, but the process by which they do it is anything but easy.

The other important aspect of qualitative research is the measurement of what I would call soft end points. These are things that are don't have any obvious physical, biological or chemical manifestation. Soft end points involve perceptions, feelings, values and so forth.

The number of red blood cells for exhibits a hard endpoints all right, but the and that tends to lend itself towards quantitative research. But if you think how the children who live with a sibling with chronic disease cope, you're going to ask a lot of questions of the children, of the parents, you are going to read narratives and so forth. This is going to all be text and you going to have to make sense of this text. It is worth the extra effort because of the richness that qualitative data provides.

:::

## Quote in support of quantitative data

* "When you can measure what you are speaking about, and express it in numbers, you know something about it, when you cannot express it in numbers, your knowledge is of a meager and unsatisfactory kind; it may be the beginning of knowledge, but you have scarely, in your thoughts advanced to the stage of science."

  + Lord Kelvin, as quoted at [Goodreads](https://www.goodreads.com/quotes/166961-when-you-can-measure-what-you-are-speaking-about-and)
  
::: notes

Here's a quote that I like, though it is really too extreme. In general, I find great value in both quantitative and qualitative data. 

Lord Kelvin said this a couple of centuries ago. This quote appears a lot of doors of different statisticians that I know. It justifies all the training we all did just did.

I know about numbers and know how make sense of them, so I am quite at home with a quote like this. But there is a counterpoint.


:::

## Quote critical of quantitative data

* "The individual source of the statistics may easily be the weakest link. Harold Cox tells a story of his life as a young man in India. He quoted some statistics to a Judge, an Englishman, and a very good fellow. His friend said, Cox, when you are a bit older, you will not quote Indian statistics with that assurance."

  + Josiah Stamp, as quoted at [Bartleby](https://www.bartleby.com/73/1768.html)

::: notes

Harold Cox told the story and is reported by guy named Josiah Stamp. Remember this quote. The process of collecting data is a process that involves social interactions. 

:::

## Quote critical of quantitative data

* "The Government are very keen on amassing statistics—they collect them, add them, raise them to the nth power, take the cube root and prepare wonderful diagrams. But what you must never forget is that every one of those figures comes in the first instance from the chowty dar [chowkidar] (village watchman), who just puts down what he damn pleases."

::: notes

That census worker whose coming up with a count of the number of people who live in certain parts of the United States, you think counting would be easy, but it is not.

A lot of subjective choices are involved with the training of the census takers. The interactions that census takers with the people they are collecting data on is quite dependent on the census taker. They try to standardize data collection as much as they can, but the process is so complex that some level of subjectivity has to creep in. Counting is a process that seems objective, but when you involve humans in the process, it changes things. I'm glad that the Census counts people as well as it does, but when you think about the process, you should recognize that quantitative data are not necessarily going to be all that the empiricists and the positivists claim that it is.

There are times (many times) when quantitative data is the best thing in the world to do. But if your research question is addressing perceptions, emotions, feelings, and values, it is really hard to do that in a way that's truly objective.

If you have to elicit information in a way that involves two human beings there are interactions. If you try to pretend that these interactions are in some sense, unbiased, and it doesn't matter whether the interviewer is male or female, I'm sorry but you're wrong. 

If I'm interviewed by female researcher and they ask certain questions about my prostate, I might not give her an honest answer. I'm not saying this to sound sexist or anything, but it's just a fact of life. How men interact with men is different than how men interact with women which is different than how women interact with women which is different than how women interact with women. People with certain racial identity interact with people of the same identity differently than they interact with people of a different racial identity.

So pretending the quantitative data is rigorous is a mistake. I'd like to think otherwise, because I spend most of my time on the quantitative side of the dichotomy. Darn it all! I need to disabuse of this notion.v

This is a point I've made several times before and which I will continue to hammer on throughout the course. There's no one right way to do statistics.

We try to remove of the influence of the researcher on the research. We try to spell out a process with an algorithm that you can follow that can be done repeatedly by different people and yet come up with the same results. But if you're constructivist you believe the truth is constructed as a social process and this means that these efforts will fail.

Should you throw up your hands and give up? Not really. You have two choices. First you can make all reasonable efforts to produce data that is objective. So blinding, for example, is something you can do that helps a lot to remove people's biases. Suppose you were doing a study where half the people had lung cancer have to people didn't and you asked both groups of how much did you smoke in your lifetime. 

If you knew that the patient had cancer, you might probe a little bit harder on some questions. "Are you sure you didn't smoke any cigarettes? Think hard now." So keeping the evaluators blinded goes a long way towards the post positivist belief that removing many of the biases will get us something that's a reasonably good approximation of the truth. 

Your other choice is to embrace the fact that researchers bring their prejudices and biases into the research. Ask the researchers to involve themselves more directly in the research process by allowing them to deviate when needed from a strict algorithm. Do it in a way where the deviations are structured in a certain way. It's not quite as easy, but when you let the researcher adapt, you often end up with a richer and fuller set of data. 

Imagine the setting, and  I use this example over and over again, about how children cope when they have a sibling with chronic disease. You  can't just put a questionnaire in front of someone and then tally up the results. You have to probe, ask questions, encourage exploration of important topics.

That's going to increase the subjectivity of results, but it's also going to improve the richness of the responses.

The thing about quantitative approaches is that when you try to reduce people in numbers, sometimes you lose something important.

When you have a research question, you have to make a choice. You can try to make it as objective as possible in a post-positivist perspective. Or you describe a process which recongizes and encourages the researcher to become part of the research in a constructivist perspective.

:::
