---
title: "Comments for MEDB 5510, Week 01"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "Defining Clinical Research Methodology"
  topic_02: "Where do research ideas come from?"
  topic_03: "Quantitative versus qualitative research"
  topic_04: "Other research dichotomies"
  topic_05: "Still more research dichotomies"
editor: source
---

## Topics to be covered

```{r}
# Preliminaries, if needed

# Keep this chunk, even if no code, so that
# params is populated from the yaml header.

# To print speaker notes, add
#   ?print-pdf&showNotes=separate-page 
#   to the end of the URL. Then open the
#   print dialog box (ctrl-P) and choose
#   Save as PDF for the printer. Other 
#   options, like Microsoft Print to PDF
#   do not seem to work.
```

-   What you will learn
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`

{{< include _crm-01-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

::: notes

How do you get started in research? First, you have to choose a problem to study. This is sometimes easy, but sometimes not so easy. This module will help you think about how to identify a research topic. It will also outline some of the fundamental choices that you will need to make as you work on your research problem. Do you want to do theoretical or applied research? Laboratory or field research? Qualitative or quantitative research? Inductive or deductive research? You should become familiar with all of these aspects of research so you can thoughtfully select the approach that makes the most sense for your topic.

In this module, you will learn how to

-   Define "clinical research methodology"
-   Select an appropriate research topic
-   Distinguish between various research approaches

:::

{{< include _crm-01-02.qmd >}}

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`
    
{{< include _crm-01-03.qmd >}}

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`
    
{{< include _crm-01-04.qmd >}}

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`
    
{{< include _crm-01-05.qmd >}}

## Summary

-   What you have learned
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`

<!---
      You have to put the title down 
      here to override the titles of
      all the include files.
--->

---
title: "Comments for MEDB 5510, Week 01"
---