---
title: "Review the many research choices you have"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Getting started, 1

-   PICO
    -   Patient group
    -   Intervention (Exposure)
    -   Control or comparison group
    -   Outcome
    
::: notes
There are three frameworks for getting started in research, PICO, FINER, and SMART. You don't have to adopt any of these frameworks, but they often are helpful.

The first framework is PICO, used primarily for hypothesis driven research, is borrowed from Evidence-Based Medicine.
:::

## Getting started, 2

-   FINER
    -   Feasible
    -   Interesting
    -   Novel
    -   Ethical
    -   Relevant
    
::: notes
The second framework is FINER. It helps you justify your research program.
:::
    
## Getting started, 3

-   SMART
    -   Specific
    -   Measurable
    -   Achievable
    -   Relevant
    -   Time bounded
-   [Who] will do [what] resulting in [measure] by [when]

::: notes
The third framework is SMART. This is commonly applied to quality improvement studies, but it can be used elsewhere.
:::

## Getting started, 4

-   PDSA (PDCA)
    -   Plan
    -   Do
    -   Study (Check)
    -   Act

::: notes
PDSA provides another framework for quality improvement studies. Think of your work as a cycle. Outline your approach (Plan), implement your approach (Do), evaluate your approach (Study), and implement what you'v lecarned (Act).
:::


