---
title: "What is a diagnostic test?"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## What is a diagnostic test?

-   Indication of disease
    -    Rapid, convenient, and/or inexpensive
-   Gold standard
    -    Indication of same disease
    -    Slow, inconvenient, and/or expensive

::: notes
A diagnostic test is a procedure which gives a rapid, convenient and/or inexpensive indication of whether a patient has a certain disease. 

In research settings, a diagnostic test is often compared to a gold standard. This is a measurement that is slower, less convenient, or more expensive than the diagnostic test, but which also gives a definitive indication of disease status. The gold standard might involve invasive procedures like a biopsy or could mean waiting for several years until the disease status becomes obvious.
:::
    
## Examples of diagnostic tests, 1 of 2    
    
-   Yale-Brown obsessive-compulsive scale
    -   Do you often feel sad or depressed?
-   SCOFF questionnaire
    -   Five yes/no questions
    -   Two or more yes responses
    
::: notes
Some examples of diagnostic tests are:

The Yale-Brown obsessive-compulsive scale, a simple yes/no answer to the following question: Do you often feel sad or depressed? In a study of stroke patients at the Royal Liverpool and Broadgreen University Hospitals (BMJ 2001; 323: 1159), this test was shown to perform well compared to a more complex measure, the Montgomery Asberg depression rating scale.

The SCOFF questionnaire asks five yes/no questions to determine whether a patient has an eating disorder.

-   Do you ever make yourself sick because you feel uncomfortably full?

-   Do you worry you have lost control over how much you eat?

-   Have you recently lost more than one stone in a 3 month period?

-   Do you believe yourself to be fat when others say you are thin?

-   Would you say that food dominates your life?

Two or more yes answers is considered a positive test. In a study of 341 consecutive patients at two general practices in southwest London (BMJ 2002; 325: 755-756), these patients were given the SCOFF questionnaire and then a formal interview based on Diagnostic and Statistical Manual of Mental Disorders, (fourth edition). The interview lasted 10-15 minutes and the interviewer did not know that score on the SCOFF questionnaire. The SCOFF questionnaire produced results that were comparable to the formal interview.
:::

## More examples

-   Rectal bleeding as a sign of colorectal cancer
-   Electrocardiogram, QTc dispersion

::: notes
Patients with rectal bleeding will sometimes develop colorectal cancer. In a study at a network of practices in Belgium (BMJ 2000; 321; 998-999), 386 patients presented with rectal bleeding between 1993 and 1994. After following these patients for 18 to 30 months, only a few developed colorectal cancer.

A standard electrocardiogram can produce a measure called QTc dispersion. In a study of 49 patients with peripheral vascular disease (BMJ 1996; 312: 874-878), all were assessed for their QTc dispersion values. These patients were then followed for 52 to 77 months. During this time, there were 12 cardiac deaths, 3 non-cardiac deaths, and 34 survivors. A value of QTc dispersion of 60 ms or more did quite well in predicting cardiac death.
:::

