---
title: "Comments for MEDB 5502, Week 07"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "To be determined"
  topic_02: "To be determined"
  topic_03: "To be determined"
  topic_04: "To be determined"
  topic_05: "To be determined"
  topic_06: "To be determined"
  topic_07: "To be determined"
  topic_08: "To be determined"
editor: source
---

## Topics to be covered

```{r}
# Preliminaries, if needed

# Keep this chunk, even if no code, so that
# params is populated from the yaml header.

# To print speaker notes, add
#   ?print-pdf&showNotes=separate-page 
#   to the end of the URL. Then open the
#   print dialog box (ctrl-P) and choose
#   Save as PDF for the printer. Other 
#   options, like Microsoft Print to PDF
#   do not seem to work.
```

-   What you will learn
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`

{{< include _b2-07-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

{{< include _b2-07-02.qmd >}}

## Live demo, ANOVA and R-squared

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`
    
{{< include _b2-07-03.qmd >}}

## Live demo, partial F test

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`
    
{{< include _b2-07-04.qmd >}}

## Live demo, stepwise regression

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`

{{< include _b2-07-05.qmd >}}

## Live demo, regression diagnostics

## Break #5

-   What you have learned
    -   `r params$topic_05`
-   What's coming next
    -   `r params$topic_06`

{{< include _b2-07-06.qmd >}}

## Live demo, multicollinearity

## Break #6

-   What you have learned
    -   `r params$topic_06`
-   What's coming next
    -   `r params$topic_07`

{{< include _b2-07-07.qmd >}}

## Break #7

-   What you have learned
    -   `r params$topic_07`
-   What's coming next
    -   `r params$topic_08`

{{< include _b2-07-08.qmd >}}

## Summary

-   What you have learned
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`
    
## Additional topics??

::: notes
-   Learning objectives
    -   Create a 2 x 2 contingency table for a diagnostic Test
    -   Define Gold Standard
    -   Define and calculate Sensitivity, Specificity, Positive and Negative Predictive Values and Positive and Negative Likelihood ratios.
    -   Define True Positive Rate
    -   Define True Negative Rate
    -   Define True Positive, True Negative, False Positive and False Negative values
    -   Identify True Positive, True Negative, False Positive and False Negative values in a contingency table.
    -   Define Prevalence
    -   Calculate Disease Prevalence
    -   Define and Calculate Positive and Negative Likelihood ratios
    -   Compare and Contrast Likelihood ratios and Predictive Values
    -   Define and explain Pre-test Probability
    -   Define and explain Post-test Probability
    -   Define the Fagan Nomogram
    -   Demonstrate correct use of a Fagan Nomogram
    -   Define a Receiver Operator Curve
    -   Explain the x axis and y axis of a Receiver Operator Curve
    -   Create a Receiver Operator Curve using SPSS or SAS and by "hand"
    -   Interpret a Receiver Operator Curve
    -   Compare two or more diagnostic tests on a Receiver Operator Curve
    -   Define the "C" statistic
    -   Define Area under the Curve
:::

<!---
      You have to put the title down 
      here to override the titles of
      all the include files.
--->

---
title: "Comments for MEDB 5502, Week 03"
---