---
title: "Review module11, McNemar's test"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Paired binary data

-   Before and after intervention
-   Left eye and right eye
-   Control matched on age, sex, race
-   Family member/same litter

## Data layout for McNemar's test

$\begin{matrix} a & b \\ c & d \end{matrix}$


-   $T = \frac{(b-c)^2}{b+c}

::: notes
To compute McNemar's test, you first need to calculate the two by two crosstabulation of the "before" and "after" measurements. 

it is arbitrary whether the rows represent the "before" measurements and the columns represent the "after" measurements or the reverse. The order of the rows and columns is also arbitrary, but you must be consistent. If the binary variable is yes/no, then you can have the first row and the first column being "yes" or you can have the first row and column being "no" but you shouldn't have the first row be "yes" and the first column be "no".

The test statistic is the difference in the off-diagonal terms squared divided by the sum of the off-diagonal terms.
:::

## Demonstrate McNemar's test in SPSS
