---
title: "Review module03, descriptive statistics"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Counts/proportions/rates

-   Counts are special type of discrete data
-   Proportion is count divided by bigger count
-   Rates is count divided by time

::: notes
Counts are a special case of discrete data. It has a lower bound of zero and often no firm upper bound. 

A proportion is a count divided by a bigger count. Typically the numerator represents a subset of the denominator. A proportion is always between zero and one.

Rates are a count divided by a measure of time. Rates can never be negative, but can sometimes be larger than one.

There are some specialized statistical methods for counts, proportions, and rates.
:::

## Errors

-   Measurement
-   Validity
-   Reliability
-   Sampling

::: notes
There are several sources of error in Statistics. Measurement error occurs typically with physical measurements and reflects the fact that these measurements are not always as precise as we would like. 

Finding ways to reduce measurement error are an important part of designing good research studies.

Errors in validity and reliability occur typically with constructs, though they can occur with physical measurements as well. A construct is a theoretical quantity that can only be measured indirectly. Validity errors occur when the indirect measurement is not an accurate representation of the theoretical construct. 

Reliability errors occur when the measurements differ by observer or over short spans of time.

Sampling error is uncertainty caused by using a sample (a subset of the population) to represent the results in the entire population.
:::

## Descriptive statistics

-   Mean, median
-   Percentiles, quartiles
-   Standard deviation
    -   Special application with normal data

::: notes
The mean and the median are both measures of central tendency. You calculate the mean by adding up all the values in the data and dividing by the sample size. The median is the middle value or the average of the two middle values after sorting the data from low to high.

Percentiles are also computed after sorting the data. They represent the value so that a fixed proportion of the data is smaller and the rest is larger. The 10th percentile is the value where roughly 10% of the data is smaller and 90% of the data is larger.

The lower quartile is the 25th percentile and the upper quartile is the 75th percentile. These two values plus the median split the data into four groups, each having roughly 25% of the data.

The standard deviation is a measure of variation. If the data is roughly normally distributed then about 68% of the data lies within one standard deviation of the mean, about 95% of the data lies within two standard deviations of the mean and almost all of the data lies within three standard deviations of the mean.
:::

## Behavior of the mean versus an individual

-   Central Limit Theorem
    -   Sample mean is approximately normal
    -   Even if individual observations are not
-   $s.e.(\bar{X})=\frac{s}{\sqrt{n}}$

## Is your data normally distributed?

-   Best approaches
    -   Q-Q plot
    -   Histogram
    -   Boxplot
-   Non-visual approaches
    -   Does mean differ only slightly from the median
    -   Is the median halfway between the two quartiles
-   For non-negative data
    -   Is the standard deviation large relative to the mean



Standard deviation divided by the square root of the sample size. 