---
title: "Review module07, independent sample and paired sample t-tests"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Two sample t-test

-   $H_0:\ \mu_1 = \mu_2$
-   $H_1:\ \mu_1 \ne \mu_2$
-   Assumptions
    -   Normality
    -   Equal variances
    -   Independence
    
::: notes
Things started getting interesting around week 7. The two sample t-test (also known as the independent samples t-test) compares the population means of two groups.

There are three key assumptions.
:::

## Test statistic and confidence interval

-   Standard error
    -   $se=S_p\sqrt{\frac{1}{n_1}+\frac{1}{n_2}}$
    -   $S_p=\sqrt{\frac{(n_1-1)S_1^2+n_2-1)S_2^2}{n_1+n_2-2}}$
-   1-$\alpha$ confidence interval
    -   $(\bar{X}_1- \bar{X}_2) \pm t(1-\alpha/2; n_1+n_2-2) \times se$
-   Test statistic
    -   $T = \frac{\bar{X}_1- \bar{X}_2}{se}$
    -   Accept $H_0$ if T is close to zero, or if CI includes 0

::: notes
The confidence interval for the difference in population means adds and subtracts a t percentile times the standard error of the difference in means.

The test statistic is the difference in sample means divided by the standard error.
:::

## Demonstrate the two-sample t-test in SPSS

## Three things you need for a power calculation

-   Research hypothesis
-   Standard deviation of your outcome measure
-   Minimum clinically important difference

::: notes
When you are planning a research study, you should select a sample size that gives you reasonable power (at least 80%, but 90% is better). The power calculation requires three things, and getting the last two, the standard deviation and the minimum clinically important difference, can be tricky.
:::

## Demonstrate power calculation in SPSS

## Paired t-test

-   Natural pairing
    -   Left eye and right eye
    -   Before and after measures
    -   Closely related familty members
    -   Litters
-   Designed pairing
    -   Matching on age, race, gender, etc.
    
## Research hypothesis

-   $\mu_D=\mu_1-\mu_2$
-   $H_0:\ \mu_D = 0$
-   $H_1:\ \mu_D \ne 0$
-   Assumptions on $D_i=X_{1i}-X_{2i}$
    -   Normality
    -   Independence
    
::: notes
The hypothesis can be written in terms of the difference in means. Note that the assumptions are about the sample differences being normal and being independent. You could have a non-normal distribution for X1 and a similar non-normal distribution for X2, and if these cancel out when you take the difference, great!

The independence assumption is that the differences are independent of one another. You do not assume that X1 and X2 are independent within a pair. In fact, you hope that they are not independent, but rather that they are positively correlated. When the pairs are positively correlated, you can get a difference with a lot less noise.
:::
    
## Confidence interval and test statistic

-   Standard error
    -   $se=\frac{S_D}{\sqrt{n}}$
-   1-$\alpha$ confidence interval
    -   $\bar{D} \pm t(1-\alpha/2) se(\bar{D})$
-   Test statistic
    -   $T=\frac{\bar{D}}{se}$
    -   Accept $H_0$ if T is close to 0 or if CI includes 0
    
## Demonstrate paired t-test in SPSS
