---
title: "Review module06, assessing normality"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Problems caused by non-normality

-   Outliers distort your perspective
-   Inaccurate Type I error rates
-   Confidence intervals too narrow or wide

::: notes
Sometimes, I think that researchers obsess too much about non-normality, but in fairness to them, it is an important issue. If your data does not follow a bell shaped curve, then several problems could happen.

First, you might see a greater degree of imprecision, reflected in very wide confidence intervals and loss of statistical power.

Second, you might have poor coverage probability. The 95% confidence interval might only reprent a 92% confidence level. The Type I error rate might be greater than 5%.

Third, and this point is not emphasized enough, is that non-normal data makes it difficult for you to extrapolate to future observations. Prediction of future events is a big part of Statistics. It is difficult even with normal data and becomes much more difficult with non-normal data.

Yes, you might say, but doesn't the Central Limit Theorem help us out? Well, yes, if the sample size is large, but it only helps with assuring accurate confidence levels and good control of the Type I error rate. Non-normal data will still often produce intervals that are too wide and tests that have too little power.
:::

## Is your data normally distributed, 1 of 2

-   Best approaches
    -   Q-Q plot
    -   Histogram
    -   Boxplot

::: notes
The easiest way to assess normality is visually. It is admittedly subjective, but objective tests like Shapiro-Wilk test are not good.
:::

## Is your data normally distributed, 2 of 2

-   Non-visual approaches
    -   Does mean differ only slightly from the median
    -   Is the median halfway between the two quartiles
-   For non-negative data
    -   Is the standard deviation large relative to the mean
-   Calculate skewness and kurtosis
-   Do not rely on tests of normality

::: notes
If you are reading a paper and the authors do not provide a graphic visualization of normality (page limits are an issue!) then there are a few non-visual approaches that can sometimes help. They are not as good as a visual approach, though.
:::

## Demonstrate how to get Q-Q plots and histograms in SPSS
