---
title: "Comments for MEDB 5501, Week 14"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "Module 01, running SPSS"
  topic_02: "Assumptions in linear regression"
  topic_03: "Calculation of sums of squares"
  topic_04: "Confidence intervals and hypothesis tests"
  topic_05: "Relationship to the correlation coefficient"
  topic_06: "Definition of residuals"
  topic_07: "Diagnostic plots"
  topic_08: "Interpretation with two independent variables"
editor: source
---

## Topics to be covered
-   What you will learn
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`

{{< include _15-00.qmd >}}

{{< include _15-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

{{< include _15-02.qmd >}}

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`

{{< include _15-03.qmd >}}

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`

{{< include _15-04.qmd >}}

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`

{{< include _15-05.qmd >}}

## Break #5

-   What you have learned
    -   `r params$topic_05`
-   What's coming next
    -   `r params$topic_06`

{{< include _15-06.qmd >}}

## Break #6

-   What you have learned
    -   `r params$topic_06`
-   What's coming next
    -   `r params$topic_07`

{{< include _15-07.qmd >}}

## Break #7

-   What you have learned
    -   `r params$topic_07`
-   What's coming next
    -   `r params$topic_08`

{{< include _15-08.qmd >}}

## Summary

-   What you have learned
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`
    
## Additional topics??

::: notes
-   Define Simple Linear Regression in terms of usage
-   Define Predictor Variable
-   Define Outcome Variable
-   Define Line of Best Fit
-   Define Slope
-   Define Y intercept
-   Define residuals
-   Explain why the residuals are squared in the regression equation
-   Define the Least Squares Method
-   Identify the type of data used in a Linear Regression Analysis
-   Explain the two main purposes of Linear Regression Analysis
-   Identify the two assumptions that must be met for a Linear Regression Analysis to be valid
-   Identify three additional assumptions that must be met for a Linear Regression Analysis to be run
-   Explain Homoscedasticity of Residuals
-   Define the assumption that must be met for a Linear Regression Analysis to be run
-   Write the Null and Alternative Hypothesis for a Linear Regression Analysis
-   Know the processes to test each assumption for a Linear Regression Analysis
-   Define Autocorrelation
-   Define the Durbin-Watson Test
-   Define the interpretation of the Durbin-Watson Test
-   Know the SPSS process for running a Linear Regression Analysis
-   Run a Linear Regression Analysis using SPSS
-   List all relevant output for a Linear Regression Analysis
-   Define R
-   Define R squared
-   Define adjusted R squared
-   Interpret R, R squared and adjusted R squared
-   Know the mathematical equation for R squared
-   Relate the significance test for ANOVA to Linear Regression Analysis
-   Explain the model test for a Linear Regression Analysis
-   Write the model equation using the Linear Regression Analysis output
-   Define B
-   Define constant
-   Understand the limits of Linear Regression Analysis
-   Correctly and completely write up a Linear Regression Analysis
:::

<!---
      You have to put the title down 
      here to override the titles of
      all the include files.
--->

---
title: "Comments for MEDB 5501, Week 14"
---