---
title: "Comments for MEDB 5501, Week 14"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_1: "Interpretation of regression slope and intercept"
  topic_2: "Relationship to the correlation coefficient"
  topic_3: "Definition of residuals"
  topic_4: "Calculation of sums of squares"
  topic_5: "Proportion of explained variation"
  topic_6: "Assumptions in linear regression"
  topic_7: "Interpretation with two independent variables"
editor: source
---

## Topics to be covered
-   What you will learn
    -   `r params$topic_1`
    -   `r params$topic_2`
    -   `r params$topic_3`
    -   `r params$topic_4`
    -   `r params$topic_5`
    -   `r params$topic_6`
    -   `r params$topic_7`

{{< include _14-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_1`
-   What's coming next
    -   `r params$topic_2`

{{< include _14-02.qmd >}}

## Break #2

-   What you have learned
    -   `r params$topic_2`
-   What's coming next
    -   `r params$topic_3`

{{< include _14-03.qmd >}}

## Break #3

-   What you have learned
    -   `r params$topic_3`
-   What's coming next
    -   `r params$topic_4`

## include _14-04.qmd

## Break #4

-   What you have learned
    -   `r params$topic_4`
-   What's coming next
    -   `r params$topic_5`

## include _14-04.qmd

## Break #5

-   What you have learned
    -   `r params$topic_5`
-   What's coming next
    -   `r params$topic_6`

## include _14-06.qmd

## Break #6

-   What you have learned
    -   `r params$topic_6`
-   What's coming next
    -   `r params$topic_7`

## include _14-07.qmd

## Summary

-   What you have learned
    -   `r params$topic_1`
    -   `r params$topic_2`
    -   `r params$topic_3`
    -   `r params$topic_4`
    -   `r params$topic_5`
    -   `r params$topic_6`
    -   `r params$topic_7`

