---
title: "Comments for MEDB 5502, Week 08"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "A simple example of survival data"
  topic_02: "Overall Kaplan-Meier curve"
  topic_03: "The log rank test"
  topic_04: "The hazard function"
  topic_05: "The Cox regression model"
  topic_06: "To be determined"
  topic_07: "To be determined"
  topic_08: "To be determined"
editor: source
---

## Topics to be covered

```{r}
# Preliminaries, if needed

# Keep this chunk, even if no code, so that
# params is populated from the yaml header.

# To print speaker notes, add
#   ?print-pdf&showNotes=separate-page 
#   to the end of the URL. Then open the
#   print dialog box (ctrl-P) and choose
#   Save as PDF for the printer. Other 
#   options, like Microsoft Print to PDF
#   do not seem to work.
```

-   What you will learn
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`

{{< include _b2-08-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

{{< include _b2-08-02.qmd >}}

## Live demo, ANOVA and R-squared

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`
    
{{< include _b2-08-03.qmd >}}

## Live demo, partial F test

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`
    
{{< include _b2-08-04.qmd >}}

## Live demo, stepwise regression

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`

{{< include _b2-08-05.qmd >}}

## Live demo, regression diagnostics

## Break #5

-   What you have learned
    -   `r params$topic_05`
-   What's coming next
    -   `r params$topic_06`

{{< include _b2-08-06.qmd >}}

## Live demo, multicollinearity

## Break #6

-   What you have learned
    -   `r params$topic_06`
-   What's coming next
    -   `r params$topic_07`

{{< include _b2-08-07.qmd >}}

## Break #7

-   What you have learned
    -   `r params$topic_07`
-   What's coming next
    -   `r params$topic_08`

{{< include _b2-08-08.qmd >}}

## Summary

-   What you have learned
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`
    
## Additional topics??

::: notes
-   Learning objectives
    -   Define Propensity Score
    -   Define propensity Score Matching
    -   Explain the main reason for the use of propensity scores
    -   Explain the use of Propensity Scores for a Treatment-Control Study
    -   List the 3 relationship between the covariate, the Outcome Variable and the Treatment assignment
    -   Define the 3 relationship between the covariate, the Outcome Variable and the Treatment assignment
    -   State the "biggest" challenge of Propensity Score calculation
    -   Define the most important step in Propensity Score calculation
    -   Explain the mathematical theory of the Propensity Score
    -   List and define the Assumptions for Propensity Score calculation
    -   Explain the problem of a Propensity Score of 0 or 1
    -   Explain the Area of Common Support
    -   Explain the need for an ideal  number of covariates for the Propensity Score calculation
    -   Explain the selection of covariates for Propensity Score Calculation
    -   List and explain the methods for matching groups using Propensity Scores
    -   List and explain the limitations/concerns of using Propensity Scores
    -   Explain the benefits of Propensity Score Matching over using a regression model for covariate control.
    -   Explain the benefits of using a regression model over Propensity Score Matching for covariate control.
:::

<!---
      You have to put the title down 
      here to override the titles of
      all the include files.
--->

---
title: "Comments for MEDB 5502, Week 03"
---