---
title: "What is a literature review?"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Learning objectives

-   To define what a literature review is and to contrast it with an annotated bibliography and a systematic overview.
-   To recognize the different approaches to organizing a literature review.

::: notes
This is the video for the third week of class. 

This is what we will cover this week.
:::

## What is a literature review? 

Definition (from your book): "An interpretation of a selection of documents (published or unpublished) on a specific topic that involves summarization, analysis, evaluation, and synthesis of the documents."

::: notes
Take a careful look at this definition.

A literature review involves summarization. You take a ten page research article and boil it down to one or two sentences.

It involves analysis. You need to gain an understanding of what is in each research paper.

It involves evaluation. You need to assess the validity of the research papers. This is synonymous with the critical appraisal step in Evidence Based Medicine.

It involves synthesis. You have to combine your knowledge of each individual study into a cohesive structure.

What all of this means is that you have to live and breath these studies. You can't summarize, analyze, evaluate, or synthesize with only a superficial understanding of these papers.
:::


## Why do a literature review?

(From your book)

-   "Identify gaps in the literature"
-   "Help to select appropriate methods for your new topic"
-   "Describe the inferences that have come from past research"
-   Other reasons???
    -   Because you have to.


::: notes
A literature review is a requirement for pretty much any research paper or presentation, for any IRB proposal, or for any grant proposal. So, you're probably doing this literature review out of a sense of obligation if nothing else.

But why would I or someone else insist on this literature review?

A literature review can and should influence your work. Even if you already have a strong idea of what you plan to do, keep an open mind about the direction of your research while doing the literature review. The literature review might change your mind about what is known and where the gaps in knowledge area. It may suggest an alternative research design or data analysis approach than you had first thought about. And it may change your impression of what the current state of knowledge is.

Even if the literature review does not help you, it is still of value to anyone who has to read and evaluate your research proposal. It gives them some background so they can understand the magnitude of the problem you are addressing, and what has been done and what still needs to be done to solve this problem.

:::

## Annotated bibliography versus the literature review 

-   Annotated bibliography

    -   Also requires summarization
  
    -   Often requires analysis and evaluation
  
    -   Lacks synthesis (no organization)

    -   Strives for completeness

::: notes
Let me mention a couple of things that have some similarities to a literature review, but which also have important differences.

An annotated bibliography is a great thing. It provides a fairly complete set of references with a brief summary of each reference. 

If you are thinking of starting a website or blog, consider developing an annotated bibliography. It will be a very popular resource because people want to know what they are going to click on before they actually click. It's also a lot easier to develop an annotated bibliography than your own original content.

Like a literature review, an annotated bibliography requires summarization. Usually the summaries are a bit longer in an annotated bibliography. In fact, in a literature review, if you find three articles that say the same thing, you lump them all together and talk about them as if they were one.

Annotated bibliographies are also like literature reviews in that most of them provide an analysis and evaluation of the articles.

The big difference is that an annotated bibliography does not try to synthesize the articles. It discussed each article individually, but does not try to organize them in a narrative flow (we'll talk about organization in just a bit).

The other difference is that in an annotated bibliography, you usually try to be comprehensive in the studies you cite. In a literature review, if you find one or two articles that make a particular point, then you don't typically need or want to include others as well.
:::


## Systematic overview versus the literature review

-   Systematic overview
    -   Systematic
    -   Exhaustive search
    -   Usually a quantitative summary
    -   Lacks synthesis

::: notes
A systematic overview (often called a meta-analysis, though there is a subtle distinction between the two) also has some similarities to a literature review.

The first distinguishing feature of a systematic overview is that it is systematic. It follows a pre-specified structure from a detailed protocol.  You require such rigidity because you want a systematic overview to be repeatable. With a literature review, you change how you search for articles and how you evaluate them as you go along. It is a very ad hoc approach.

A systematic overview attempts to get all studies related to a particular research hypothesis and this hypothesis is usually drawn more narrowly than a literature review. In a literature review, by contrast, you might talk first about defining studies that define the magnitude of your health care problem and then switch to interventions that have been tested in your area. The systematic overview is likely to consider only studies within a certain time range, but your literature review might provide some much earlier studies to provide some historical context.

Systematic overviews often contain a quantitative summary (the meta-analysis) while literature reviews almost always use a qualitative approach.

Systematic overviews do not consider any synthesis (other than the quantitative summary) and just toss all of the studies into a big pot and stir.

The other distinction is that a systematic overview works with an almost obsessive fervor to identify every possible study in a topic. One of the greatest threats to the validity of a systematic overview is publication bias, and you have to work very very hard to overcome this.

For what it's worth, there has been a call in the research community to replace the literature review with a systematic overview for the benefit of an IRB submission. The systematic overview would establish whether sufficient evidence has already accumulated to make the proposed research unnecessary (and therefore unethical). This suggestion has not really been adopted anywhere, as far as I know, but it is interesting.
:::
