---
title: "An organizing structure to your literature review"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Synthesizing

-   Organization of a literature review
    -   Chronologic (warning: can be boring!)
    -   From general to specific
    -   Thematic
-   End with your research

::: notes
One way of organizing your review might by chronological. This is appealing if new theories or new approaches emerge over time. But beware, because a chronological list can sometimes come across as dull.

The approach I like best (and your book also likes it) is to move from the general to the specific. There are several directions you can go, but one way would be talking about the disease, talking about a particular treatment of the disease, and then talking about that treatment in a particular subpopulation. Of course, talking about the disease, then a subpopulation and then a treatment within that subpopulation also works.

You start with the general because that is what your reader is most likely to be familiar with. As you make things more specific, you draw them in to the need for your research.

Whichever organizational approach you choose, your last paragraph summarizes everything and leads into the work you plan.
:::


## Example of general to specific

1st paragraph. "African Americans represent nearly 45% of new HIV cases each year (1–2)."

2nd paragraph. "The Black Church is a powerful institution with a history of mobilizing African American communities for social change (5)..."

3rd paragraph. "Studies suggest many African American faith leaders are willing to provide HIV education and testing for their church/community members (14–17)..."

    -   Berkley-Patton et al 2016. 


## Synthesizing

-   Possible themes
    -   Consensus, disagreements, the unknown
    -   Problem, old remedies, new needs
    -   Supportive, then non-supportive
    -   Methodologies
    -   Theories
    -   Schools of thought

::: notes
There are more possible themes than I could mention, but here are a few examples. 

Start with consensus (questions where everyone agrees on the correct answer), then list disagreements (questions with debates among competing answers), and end with the unknown (questions with no answers yet).

Or say what the problem is, say what has already been done, and say what needs to be done.

Or offer a thesis and group your references into two sections, articles that are supportive of your thesis and articles that are not supportive.

You might organize your articles into groups sharing common methodologies. In a study of mitigation of home exposures that might exacerbate asthma, the studies might be grouped by those that study a physical intervention (like improved ventilation) and by those that study a chemical intervention (spraying for dust mites). 

In a review of behavioral change, you might organize articles by the different theories of change (Lewin, Rogers, or Spradley) that they rely on. 

Some studies of child welfare management might utilize the attachment theory while others might use crisis intervention theory or social construction theory.

It's really hard to give examples here because there are so many different thematic organizations that you can choose from.
:::

## Some last thoughts

-   Revisit your literature review after writing the discussion section of your paper.
-   Standard format for a thesis. 

::: notes
You will revisit your literature review after you've collected the data, written your results and written your discussion section. The discussion section talks about the strengths and weaknesses of your particular study and places your study in a broader context. When you do this, you may notice some gaps or inconsistencies in your literature review.

There is a standard format for the literature review for a thesis. This is more detailed than what you might put in a paper.
:::
