---
title: "See title at the bottom"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
params:
  topic_01: "What is covariate imbalance?"
  topic_02: "Indicator variable coding"
  topic_03: "Mathematical model"
  topic_04: "Assumptions"
  topic_05: "To be determined"
  topic_06: "To be determined"
  topic_07: "To be determined"
  topic_08: "To be determined"
editor: source
---

## Topics to be covered

```{r}
# Preliminaries, if needed

# Keep this chunk, even if no code, so that
# params is populated from the yaml header.

# To print speaker notes, add
#   ?print-pdf&showNotes=separate-page 
#   to the end of the URL. Then open the
#   print dialog box (ctrl-P) and choose
#   Save as PDF for the printer. Other 
#   options, like Microsoft Print to PDF
#   do not seem to work.
```

-   What you will learn
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`

{{< include _b2-03-01.qmd >}}

## Break #1

-   What you have learned
    -   `r params$topic_01`
-   What's coming next
    -   `r params$topic_02`

{{< include _b2-03-02.qmd >}}

## Live demo, `r params$topic_02`

## Break #2

-   What you have learned
    -   `r params$topic_02`
-   What's coming next
    -   `r params$topic_03`
    
{{< include _b2-03-03.qmd >}}

## Live demo, `r params$topic_03`

## Break #3

-   What you have learned
    -   `r params$topic_03`
-   What's coming next
    -   `r params$topic_04`
    
{{< include _b2-03-04.qmd >}}

## Live demo, `r params$topic_04`

## Break #4

-   What you have learned
    -   `r params$topic_04`
-   What's coming next
    -   `r params$topic_05`

{{< include _b2-03-05.qmd >}}

## Live demo, `r params$topic_05`

## Break #5

-   What you have learned
    -   `r params$topic_05`
-   What's coming next
    -   `r params$topic_06`

{{< include _b2-03-06.qmd >}}

## Live demo, `r params$topic_06`

## Break #6

-   What you have learned
    -   `r params$topic_06`
-   What's coming next
    -   `r params$topic_07`

{{< include _b2-03-07.qmd >}}

## Live demo, `r params$topic_07`

## Break #7

-   What you have learned
    -   `r params$topic_07`
-   What's coming next
    -   `r params$topic_08`

{{< include _b2-03-08.qmd >}}

## Live demo, `r params$topic_08`

## Summary

-   What you have learned
    -   `r params$topic_01`
    -   `r params$topic_02`
    -   `r params$topic_03`
    -   `r params$topic_04`
    -   `r params$topic_05`
    -   `r params$topic_06`
    -   `r params$topic_07`
    -   `r params$topic_08`
    
## Additional topics??

::: notes
-   Learning objectives
    -   Explain when an ANCOVA would be used to analyze data
    -   Explain the purpose of including covariates in an ANCOVA
    -   Identify the impact of controlling for a covariate on variance, power and the F-ratio
    -   Explain the data requirements for an ANCOVA
    -   Set up a data set for an ANCOVA
    -   Write a research question forn ANCOVA
    -   Write the Null and Research Hypotheses for an ANCOVA
    -   List the assumptions for an ANCOVA
    -   Explain the tests for the assumptions for an ANCOVA
    -   Run the assumptions tests for an ANCOVA
    -   Interpret the assumptions tests for an ANCOVA
    -   Run a complete ANCOVA
    -   Explain, using output, how to note the influence of the covariate
    -   Summarize the interpretation of an ANCOVA
:::

<!---
      You have to put the title down 
      here to override the titles of
      all the include files.
--->

---
title: "Comments for MEDB 5502, Week 03"
---