---
title: "Hypothesis testing"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Pop quiz

-   A research paper computes a p-value of 0.45. How would you interpret this p-value?
    -   Strong evidence for the null hypothesis.
    -   Strong evidence for the alternative hypothesis.
    -   Little or no evidence for the null hypothesis.
    -   Little or no evidence for the alternative hypothesis.
    -   More than one answer above is correct.

::: notes

I gave a talk about ten years ago, and I had a "pop quiz" to start out the talk. It turns out that I was a bit careless in how I worded the question, but I decided to keep it in for future talks about p-values to help illustrate an important point. I won't ask you for the answer just yet, but here is the question.

A research paper computes a p-value of 0.45. How would you interpret this p-value? 

Read the possible answers and chose the correct one. 
:::

## Another question

-   A research paper computes a confidence interval for a relative risk of 0.82 to 3.94. What does this confidence interval tell you that the result is:
    -   statistically significant and clinically important.
    -   not statistically significant, but is clinically important.
    -   statistically significant, but not clinically important.
    -   not statistically significant, and not clinically important.
    -   ambiguous.


::: notes

Here's another question to toss out, but this time it is not poorly worded.

A research paper computes a confidence interval for a relative risk of 0.82 to 3.94. What does this confidence interval tell you.

The result is statistically significant and clinically important, is not statistically significant, but is clinically important, and so forth. The last answer, the result is ambiguous, is the correct one, which you'll see in a little bit.

By the way, if you weren't writhing in the floor in agony when you saw this interval, I want to change that.

:::

## What is a population?

-   A population is a collection of items of interest often defined in terms of
    -   demography,
    -   geography,
    -   occupation,
    -   time,
    -   care requirements,
    -   diagnosis, or 
    -   some combination of the above.

::: notes

Here's a definition of a population that I found somewhere but then I lost the link. So if anyone ever runs across this list of characteristics of a population, please let me know. It is too clever a list for me to have figured it out by myself.

A population is a collection of items of research. In clinical research, the population is often a collection of people, sharing some common features. They may all be in the same demographic group, the may all come from the same area, they may all have the same job, they may be getting the same type of medical care, they may have the same diseases, or it may be a combination of these items.

:::

## Example of a population

Population: All infants born in the state of Missouri during the 1995 calendar year who have one or more visits to the Emergency Room during their first year of life.

::: notes

Here's an example that hits on about all these. All infants born in the state of Missouri during the 1995 calendar year who have one or more visits to the Emergency Room during their first year of life.

Let's look at the different pieces.

All infants (demography)

born in the state of Missouri (geography)

during the 1995 calendar year (time)

who have one or more visits to the Emergency Room (care requirements)

during their first year of life (time, again)

:::

## What is a sample?

-   A sample is a subset of a population
    -   Small and manageable
-   Is your sample representative?
-   Your goal
    -   Make inferences about the population
    -   Using information from the sample
  
::: notes

A sample is a subset of a population. Usually it is of a much smaller size than the population. It has to be small enough to be manageable.

The primary goal of much research is to use information collected from a sample to try to characterize a certain population. As such, you should pay a lot of attention to how representative the sample is of the population.

If there are problems, with representativeness, consider redefining your population a bit more narrowly. For example, a sample of 85 smokers between the ages of 13 and 18 in Rochester, Minnesota who respond to an advertisement about participation in a smoking cessation program might not be considered representative of the population of all teenage smokers, because the participants selected themselves. The sample might be more representative if we restrict our population to those teenage smokers who want to quit.

:::

## More definitions for hypothesis testing

-   Parameter
    -   Computed for a population
    -   Almost always unknown
-   Statistic
    -   Computed for a sample
    -   Estimate of population parameter
-   Sampling error  
  
::: notes

A parameter is a number computed from a population. Since the population is often very large, it is often impossible to compute a parameter.

A statistic is a number computed from a sample. Since the sample is small enough to be manageable, the values of the statistic are computed with the hope that they will be good estimates of the corresponding population parameter.

Sampling error is the uncertainty created by the sampling process.

:::

## Hypotheses

-   Null hypothesis
    -   Designated by $H_0$
    -   No change, no effect
-   Alternative hypothesis
    -   Designated by $H_a$
-   Decision rule

::: notes

Researchers will often designate a null and alternative hypothesis. The null hypothesis (H0) is traditionally reserved for a hypothesis involving no effect, no change, or no trend. Let me emphasize that this is no change in a parameter.

The alternative hypothesis implies some type of change, either an improvement or decrement. It could also imply some type of association: a positive association (as one variable increases, the other variable also increases), or a negative association (as one variable increases, the other variable decreases).

Hypotheses are statements about population parameters. Because you new know exactly what a parameter is, you can never state with certainty whether a hypothesis about a parameter is true or false. Remember this, as it becomes important later.

The decision rule is a statement about what particular values in the sample would lead you to accept the null hypothesis and what values would lead you to reject the null hypothesis.

:::

## Comparison of continuous outcome for two populations

-   Most common research problem
-   Population parameters ($\mu_1$ and $\mu_2$)
-   Sample statistics ($\bar{X}_1$ and $\bar{X}_2$)
-   $H_0 \ \mu_1-\mu_2=0$ 
-   Accept $H_0$ if $\bar{X}_1-\bar{X}_2$ is close to zero.

::: notes

The most frequent hypothesis involves a comparison of continuous outcomes between two groups, a treatment group and a control group. These are designated by the subscripts 1 and 2, but there is no standard that says that 1 is the treatment and 2 is the control. It is just as likely to be the reverse. You have to look for some context to make sure you know which subscript is which.

The null hypothesis is that the difference in population means is zero. You compute the difference in sample means and accept the null hypothesis if that difference is close to zero.

How close is close? It depends on how much sampling error you have.

Example: In a study of nilvadapine in Alzheimer disease, this drug was compared to placebo on the one year decline in cognition, as measured by the Alzheimer's Disease Assessment Scale Cognitive Subscale-12. The null hypothesis was that the average difference in cognitive decline between the drug and placebo was zero. The decline was 6.41 units in the placebo group and 5.75 in the control group, a difference in the sample of 0.66. Since the difference in the two means was close to zero, the researchers accepted the null hypothesis. They concluded "The results do not suggest benefit of nilvadipine as a treatment in a population spanning mild to moderate Alzheimer disease."

:::

## Comparison of binary outcome for two populations

-   Population parameters ($\pi_1$ and $\pi_2$)
-   Sample statistics ($p_1$ and $p_2$)
-   $H_0 \ \pi_1-\pi_2=0$ 
-   Accept $H_0$ if $p_1-p_2$ is close to zero.

::: notes

Another common hypothesis involves a comparison of binary outcomes between two groups, a treatment group and a control group. The population parameters are proportions instead of means, but otherwise the concept is the same.

Close to zero, as before, means close to zero relative to the amount of sampling error.

Example: in the same study, the researchers hypothesized that the difference in proportions for patients experiencing serious adverse events was zero. The sample proportions were 20% (50/252) and 16% (42/257). Since the difference in proportions was small, the researchers accepted the null hypothesis and concluded that "Nilvadipine appeared to be safe and well tolerated"

:::

## Regression models

-   Population parameters, $\beta_0$ and $\beta_1$
    -   $\beta_1$ quantifies a relationship
    -   $\beta_1=0$ implies no relationship
-   Sample statistics $b_0$ and $b_1$
-   $H_0 \ \beta_1=0$
-   Accept $H_0$ if $b1$ is close to zero

::: notes

I'll talk a lot about regression models later, but let me introduce a hypothesis involving a regression model. Typically, but not always, a regression model has an intercept term and a slope term. The slope term quantifies the relationship between your independent variable and your dependent variable. If the population parameter is zero that means there is no relationship in the population. Like the other models, you compute a sample statistic and accept the null hypothesis if that sample statistic is close to zero.

Example: in a study of endothelial function and cognitive performance in patients with coronary heart disease, the researchers hypothesized that there was no linear relationship between change in reactive hyperemia index (RHI) and the change in overall cognition. The regression coefficient was 0.55 which was not close to zero, so the researchers rejected the null hypothesis and concluded that "an increased RHI was significantly associated with an improvement in overall cognition."

Saleem M, Herrmann N, Dinoff A, et al. Association Between Endothelial Function and Cognitive Performance in Patients With Coronary Artery Disease During Cardiac Rehabilitation. Psychosom Med. 2019;81(2):184–191. doi:10.1097/PSY.0000000000000651.

Regression models are quite flexible. They can incorporate a variety of measurements for your outcome variable and can provide for risk adjustments to your outcome variable.

This is not a data analysis class, but I do want to provide you with enough information so you can write a good data analysis plan. More likely than not, your data analysis plan will involve a regression model of some type.

:::

