---
title: "13-11 Qualitative data analysis"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Analysis of Qualitative Data-resources

-   Typically, a one-hour interview requires a minimum of three to four hours (or more) of analysis.
-   Involve the participants in the process, especially for narrative research.
-   Tools:
    -   focus groups
    -   semi-structured interviews
    -   participant observation
    -   archival records
  

::: notes

When you are planning a qualitative study, expect a lot of time in data preparation and analysis, about three to four hours for every hour of interviews.

You want to involve the participants in the design. This means letting them determine how the questions and the data collection might evovle over time.

Qualitative data is usually collected as part of a focus group, semi-structured interviews, participant observations (watching the process of delivery of health care), and analysis of records (meaning items with textual information).

:::

## Inductive process
-   Start with the specific (raw data / transcript)
    -   Develop a theoretical framework from the data
    -   Conceptual categories emerge from the data
    -   Iterative process
-   Define the process
    -   Who does the work
    -   Privacy protections
    -   How you will adapt

::: notes

Quantitative analysis is almost always structured and defined in detail prior to data collection. But qualitative analysis is different. You are trying to build a theoretical frame work from data, so you are moving from specific data to a generality. This is known as inductive research. You are using small pieces of text to develop broad themes and establish an overarching pattern or framework.

You data collection may change as you collect information. I was helping a group of nurses who were running some focus groups (I didn't do too much other than observe from a distance). A big pattern emerged with the very first focus group. There was a generational difference in norms and expectations. So much so that the first focus group almost devolved into a shouting match. So the nurses decided to ask lots of questions about generational issues and they also decided wisely to separate the boomer generation from the Xers.

So if things can and should change as you collect data, how do you write a methods section? You have to focus on the process. Well there are small things, such as who does the questions in the interviews, how the interviews will be recorded and transcibed, and so forth. You should mention privacy protections.

Most importantly, if you expect to let the early data drive how you will collect later data collection efforts, say this explicitly and explain what you will be looking for as you decide how and when to make mid-course adaptations.

:::

## Analysis process for qualitative data

-   Your research question is only your starting point.
-   Don't let your question blind you to new information
-   Build themes before you complete your data collection
    -   Check back against the  raw data
    -   Look for negative examples
    -   Don't ignore infrequently voiced themes
-   When have you achieved saturation?

::: notes

Software allows you to go back and forth between themes and the original text. Cross-referencing is important. Find examples easily. It helps provide validity checks. Does someone agree with your categorization.

Categories need to be faithful to the data. This is internal validity. But you need to place this in a broader understanding.

You need to be careful about trying to quantify this too much. Keep in mind that just because someone talks about something a lot does not mean that this is the most important thing to them. The most important thing might be something that people are uncomfortable talking about.

Phrasing of the person versus observations generated by the researcher. Labels should be considered as provisional as you work with more complete information. It is an iterative process. Go back to original data. You're looking at the specific of what's been told versus a broader understanding.

Establishing the criteria may depend on how many people are doing the coding. If you don't have a pre-existing structure, the coding may evolve and may involve 100% review (both raters review everything and resolve discrepancy). Then a third person does an audit.

The point at which you are not gaining any new insight, no new categories being identified, no new relationships being defined. Saturation is a way to assess your sample size. Have you gotten a representative amount of data. 

Really important to keep notes of the coding and analysis process, so you can check your work. Allows you to do qualirty checks on the process.

:::


## Coding the texts

-   Balancing act 
    -   Level of creativity by coder to identify categories/relationships
    -   Must reflect the informants thoughts
    -   Audit of the coding by an independent person can check for the match between the coding and the source information
-   Look for "negative cases"

::: notes

The data from a qualitative analysis is a stream of words, broken into small snippets of text. You need to assign each of these snippets to one or more categories. Software can help with this, but you need to think carefully about your role in the analysis. You can't be a disinterested bystander. 

When you analyze qualitative data, you want to think intelligently about the data in front of you but you don't want to force your pre-conceived ideas on top of the data that you collect. You need to remain true to what the participants are telling you.

Coding the data is, by necessity, a subjective process. You should plan on having two people code the data into categories independently. You also need an auditor, someone who looks critically at the match between the raw text and the themes you have developed.

One way to avoid pre-conceptions is to be constantly on the lookout for negative cases, cases that would tend to disprove any conclusions you might be tempted to draw prematurely from the data.

:::

## What goes in the methods section of a qualitative study

-   Recruitment process
-   Structure of the interview/focus group
-   Recording and transcription details
-   Software used to create categories
-   Process to insure reliability
    -   Multiple raters
    -   Adjudication of disagreement
    -   Other audits
  
::: notes

The methods that you document in a qualitative study are quite different than those you use for a qualitative study. Here are some of the elements that you need to talk about.

:::
