---
title: "External validity"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## External Validity 

-   Population external validity
    -   Representative sample
  	+ Few or no restrictions
  	+ Few or no dropouts
-   Ecological external validity
	+ Naturalness
	    -   Setting
	    -   Procedures

::: notes

:::

## Distinction between internal and external validity

-   Sampling process influences external validity
    -   Random samples versus non-random samples
-   Treatment allocation influences internal validity
    -   Randomized design versus non-randomized design

::: notes

External validity is influenced by the sampling process. Internal validity is influenced by the allocation of this sample to treatment groups.

:::

## Trade-offs between internal and external validity

-   High degree of control
    -   Avoid issues of equivalence
    -   Unnatural setting
-   Low degree of control
    -   More chances of contamination
    -   Closer to how medicine is practiced.


