---
title: "Overall Kaplan-Meier curve"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Worcester Heart Attack Study, 1

```{r}
#| message: false
#| warning: false
#| label: 08-02-setup

library(ggfortify)
library(glue)
library(readr)
library(survival)
library(tidyverse)
library(yaml)

load("../data/module08.RData")
```

```{r}
#| label: 08-02-yaml-a

f0 <- "https://raw.githubusercontent.com/pmean"
f1 <- "data/refs/heads/main/files"

dd <- read_yaml(glue("{f0}/{f1}/whas500.yaml"))
cat(as.yaml(dd["data_dictionary"]))
cat(as.yaml(dd["description"]))
i <- 0
```

::: notes

:::

## Worcester Heart Attack Study, 2

```{r}
#| label: 08-02-yaml-b

cat(as.yaml(dd$vars[1:3]))
```

::: notes

:::

## Worcester Heart Attack Study, 3

```{r}
#| label: 08-02-yaml-c

cat(as.yaml(dd$vars[4:6]))
```

::: notes

:::

## Worcester Heart Attack Study, 4

```{r}
#| label: 08-02-yaml-d

cat(as.yaml(dd$vars[7:8]))
```

::: notes

:::

## Worcester Heart Attack Study, 5

```{r}
#| label: 08-02-yaml-e

cat(as.yaml(dd$vars[9:10]))
i <- i+1
```

::: notes

:::

## Worcester Heart Attack Study, 6

```{r}
#| label: 08-02-yaml-f

cat(as.yaml(dd$vars[11:12]))
```

::: notes

:::

## Worcester Heart Attack Study, 7

```{r}
#| label: 08-02-yaml-g

cat(as.yaml(dd$vars[13:14]))
i <- i+1
```

::: notes

:::

## Worcester Heart Attack Study, 8

```{r}
#| label: 08-02-yaml-h

cat(as.yaml(dd$vars[15:17]))
i <- i+1
```

::: notes

:::

## Worcester Heart Attack Study, 9

```{r}
#| label: 08-02-yaml-i

cat(as.yaml(dd$vars[18:20]))
i <- i+1
```

## Worcester Heart Attack Study, 9

```{r}
#| label: 08-02-yaml-j

cat(as.yaml(dd$vars[21:22]))
i <- i+1
```

::: notes

:::

## Event count

```{r}
event_count
```

::: notes

:::

## Overall Kaplan-Meier curve

```{r}
km_overall
```

