---
title: "Syllabus for MEDB 5505, Introduction to R"
author: "Steve Simon"
output: html_document
---

## Course information

This is an on-line class taught, starting on Tuesday, January 17, 2023 and ending on Friday, May 12, 2023.

### Your instructor

Your instructor is Steve Simon in the Department of Biomedical and Health Informatics. My phone number is 816-235-6617 and my email is simons@umkc.edu. My office is M5-117, located on the fifth floor of the School of Medicine building in the suite of offices for Biomedical and Health Informatics.

### Catalog information

**Course Title**: Introduction to R

**Credit Hours**: 1 credit hour

**Prerequisites**: none

**Course Attributes**: graduate research training

**Course Format**: Lecture, Discussion, and individual activities

**Course Instructional Mode**: OA (Online Asyncronous class instruction); material posted on Canvas course site will support all course activities.

### Course Description

To be added.

### Course Topics

To be added.

### Introduction

To be added.

### Course Objectives

To be added.

### Student Learning Objectives

At the end of this course, you will be able to:

+ Download and install R on personal computer.
+ Identify unusual data values and missing values.
+ Summarize data using means, standard deviations, and percentages.
+ Read delimited and fixed width format files.
+ Produce data visualizations such as histograms, boxplots, and scatterplots.

### Course Requirements

Students are responsible for reading all assignments from the text, Canvas material, internet materials, and instructor provided resources before the class period in which they are to be discussed. Each student will complete Human Subjects training, assignments, a research proposal, and an oral presentation of the research proposal that will include poster material.

### Course Framework

To be added.

### Class structure

In general, each class session will consist of a mixture of recorded material available on Canvas as preparation for the session, individual assignments, and discussion/activities that are related to the topic and are completed either individually, within pairs, or within small groups of students. The lecture material is designed to supplement the information assigned from the textbook and other sources.

### Required Materials

There is no required textbook for this class.

### Recommended Materials

To be added.

### Resources

To be added.

### Course Evaluation

Completion of the confidential course evaluation at the end of the semester is available for the course and strongly encouraged. You will receive information about completing the evaluation from the Department office towards the end of the semester.

Assignments
Schedule

The detailed listing of topics, assignments, and deadlines is shown in the Course Overview document in the “Course Content” section of the course Canvas site.

A calendar showing all dates for submissions (assessment items, assignments, final project oral presentation, and final project written proposal) is shown in the Calendar document in the "Course Content" section of the course Canvas site.

Evaluation Criteria

Participation via discussion boards, 3 points each, with a one point deduction for late submissions.

Homework assignments, 20 points each, with a one point deduction for late submissions.

Grading criteria

This class is graded credit/no credit (also know as pass/fail). A passing grade will be 80% or better.

If a student feels that he/she has been unfairly graded, information on the appeal process can be found in the academic regulations information.

Submission format

Unless otherwise noted, all material that is submitted to Dr. Simon must be submitted via the course Canvas site and should be .pdf format. If you have difficulty producing pdf format files, alternate formats may be acceptable, but please clear this in advance. All files sent to Dr. Simon must include the student’s name in the filename.

Canvas Discussions

During the semester, you will be expected to participate in online discussions through the course Canvas site. Online discussion forums will provided the basis for discussions and activities that normally take place during an on-campus class period. Your engagement in the discussions will be reflected in the points you earn for participation. The minimum expectation is that you will respond to the topic, using the information you have read and/or the material presented in the recordings. Full participation in the discussion topics will be demonstrated by responses you make to the entries made by other students as well as the content of your own posting, and making these contributions in a timely manner (first posting must be made by Sunday midnight following the posting of the forums. A vital discussion board should include responses between students that expand on the original posting. Think of this as the interchange that occurs when we are all in the same room.

When a discussion topic is posted, please add your contribution by replying to the original topic. When you are responding to another student’s posting, use the reply function.

I will regularly assign a student to be the participation leader in a specific discussion forum. The leader is expected to respond to each posting, adding to the discussion as appropriate and findings links between individual postings in a way that adds value to the overall discussion. The quality of what you do when you are the participation leader will be factored into the participation part of the course evaluation.

Discussion forums

You are expected to complete the readings prior to class and be prepared for discussion. A portion of the course grade will be based on discussion board participation. It is VERY IMPORTANT to keep these discussions contemporaneous. Please post your discussion comments by the due date.


## Policies

### Canvas

Lecture material will be posted as videos and Powerpoint handouts, including speaker notes, will be available for download. Students should do the required reading prior to viewing the videos to get the maximum benefit.

Additional materials will be made available in electronic format on the Canvas website. Announcements and schedule updates will also be posted on the website.

Many materials on the Canvas website can be read and/or printed with a standard web browser. Other items require Adobe Acrobat Reader to view.

Acrobat Reader may be downloaded for FREE from the Adobe website.

### E-mail

You will be required to use a UMKC e-mail account for correspondence in this class. The instructor will not be responsible for the receipt of e-mails that are sent to locations other than those ending with "umkc.edu."

Any files that are submitted to an instructor via email MUST include the student’s name in the filename.

### Discussion Board Guidelines - General Information

The purpose of the discussion board forum is to engage students in applying the concepts of this course in an exchange of ideas and opinions that is open, honest, and that stimulates transference of ideas to your own area of expertise and interest. Discussion board conversations also serve to build a sense of community among students in the class for the purpose of examining how the concepts we are studying are relevant to our own experiences. In the best tradition of the value of learning from each other, the following guidelines should guide us all as we participate in these discussions:

Participants should listen to others respectfully. Remember that when communicating via the computer screen, you do not have the benefit of voice intonation, facial expressions, body language or gestures to interpret the meaning behind the words. The same words spoken orally in different manners can mean different things. Remember this and give the person the benefit of the doubt when interpreting discussion board posts. Take your responsibilities seriously and offer meaningful feedback. Disagreements should focus on ideas and concepts, not the individual posting to the discussion board. If you disagree with what another student has written, strive to critique ideas in a respectful and constructive manner. When a disagreement occurs, attempt to understand other person's perspectives rather than to simply criticize them. Treat other students with the same respect and courtesy that promotes the same thoughtful and fair treatment that is supportive of face to face discussions.

Intervene politely if someone is being disrespectful or unfair to others. If you find something on the Discussion Board that strikes you as unacceptable in either tone or content, gently share your concern with the poster AND be sure to let the course instructor know about it as soon as possible Usually this kind of thing is the result of some kind of accident or misunderstanding, and I will make sure that it gets cleared up as soon as possible.

Keep the content of posts relevant to the topic. While the tone of your posts may be informal and genial, the discussion board is not a chat room. If necessary for personal messages, please use Mail or other forms of direct contact.

Use language, spelling and grammar that are appropriate to an educational setting. Avoid use of overly technical or discipline specific language, slang or Internet shorthand, and remember to proofread work prior to posting it for the class to read. Strive for proper spelling and grammar. Use complete sentences. Do not "shout" (i.e., type in capital letters).

Read and Reply. Note that your replies to others are just as important as the expression of your own initial thoughts about the topic. Take time to read what others have written and to give them relevant feedback when appropriate. Even if you have completed the requirements for posting in a given week, go back and see what others have written since you were last there.

Please be sure to bring any problems or suggestions regarding effective and courteous use of the discussion board to the attention of the course director.

### Statement on Expectations Regarding Student Conduct

In order to maintain a proper learning environment within the class, it is important for all students enrolled in this course to treat both the faculty and their peers with courtesy, civility and respect. Conduct for which students are subject to sanctions includes academic dishonesty, such as cheating, plagiarism, or sabotage.

Students whose behavior is deemed disruptive by their instructor may be told to leave the classroom for the remainder of the session. Zero participation points will be earned for any weekly discussion activities when a student is told to leave the discussion.

Please refer to the UM System standard of conduct for more information.

### Academic honesty

The Board of Curators of the University of Missouri recognizes that academic honesty is essential for the intellectual life of the University. Faculty members have a special obligation to expect high standards of academic honesty in all student work. Students have a special obligation to adhere to such standards. Academic dishonesty, including cheating, plagiarism or sabotage, is adjudicated through the University of Missouri Student Conduct Code and Rules of Procedures in Student Conduct Matters.

Conduct for which students are subject to sanctions includes academic dishonesty, such as cheating, plagiarism, or sabotage. In the event misconduct is confirmed, the students will receive 0 points on the exam or assignment. If academic dishonesty is admitted or confirmed by evidence the faculty are required to report the incident to the Assistant Dean for Graduate Studies, who will meet with the faculty member and student to review the event and then determine whether it should be further referred to the Dean of the School of Graduate Studies.

Students enrolled in this course assume an obligation to behave in a manner compatible with the University’s function as an educational institution as described in the University Collected Rules and Regulations Chapter 200 Student Conduct, section 200.010 Standard of Conduct. Conduct for which students are subject to sanctions includes academic dishonesty, such as cheating, plagiarism, or sabotage. Conduct for which students are subject to sanctions are outlined as follows:

The term cheating includes but is not limited to: (i) use of any unauthorized assistance in taking quizzes, tests, or examinations; (ii) dependence upon the aid of sources beyond those authorized by the instructor in writing papers, preparing reports, solving problems, or carrying out other assignments; (iii) acquisition or possession without permission of tests or other academic material belonging to a member of the University faculty or staff; or (iv) knowingly providing any unauthorized assistance to another student on quizzes, tests, or examinations.

The term plagiarism includes, but is not limited to: (i) use by paraphrase or direct quotation of the published or unpublished work of another person without fully and properly crediting the author with footnotes, citations or bibliographical reference; (ii) unacknowledged use of materials prepared by another person or agency engaged in the selling of term papers or other academic materials; or (iii) unacknowledged use of original work/material that has been produced through collaboration with others without release in writing from collaborators. In addition, the Department of Biomedical and Health Informatics includes self-plagiarism in their expanded definition.

Self-plagiarism is reuse of an existing paper that has been submitted for credit in a different course without prior discussion and consent of the course director.

The term sabotage includes, but is not limited to, the unauthorized interference with, modification of, or destruction of the work or intellectual property of another member of the University community.

To ensure academic integrity and prevent plagiarism, UMKC has purchased the Internet-based Turn It In. This site allows faculty and students to submit papers online to examine a paper's originality. The site compares submitted papers with several proprietary algorithm databases to check for plagiarism. The course director reserves the right to have student assignments reviewed on Turnitin.com in this course. Submissions will have all identifying student information (name, student ID number etc.) removed from the submission to ensure that student's rights are protected.

Academic Inquiry, Course Discussion and Privacy: University of Missouri System Executive Order No. 38 lays out principles regarding the sanctity of classroom discussions at the university. The policy is described fully in Section 200.015 of the Collected Rules and Regulations. In this class, students may make audio or video recordings of course activity unless specifically prohibited by the faculty member. However, the redistribution of any audio or video recordings of statements or comments from the course to individuals who are not students in the course is prohibited without the express permission of the faculty member and of any students who are recorded, including those recordings prepared by an instructor. Students found to have violated this policy are subject to discipline in accordance with provisions of Section 200.020 of the Collected Rules and Regulations of the University of Missouri pertaining to student conduct matters.

Attendance Policy

Students are expected to attend and participate in classes. Advance notice of attendance policies of academic units and individual instructors should be given, and such notice should be in writing. Students should notify instructors of excused absences in advance, where possible. Students who have an excused absence are expected to make arrangements with instructors for alternative or make-up work. Such arrangements should be made in advance of the absence, where possible. Instructors should accommodate excused absences to the extent that an accommodation can be made that does not unreasonably interfere with the learning objectives of the course or unduly burden the instructor. Attendance policies shall be applied in a non-discriminatory manner.

Discrimination

The course faculty is committed to creating and maintaining a supportive learning environment. If at any time you find yourself in an environment that does not support learning, it is best to first contact the course faculty. If faculty members are unable to resolve the situation for you, you may contact: the Chair of the Department, the Associate Dean for Student Affairs, Dr. Brenda Rogers, SOM Rm M4-207, rogersbr@umkc.edu, (816) 235-1782; Sam Turner, Office of Diversity & Community Partnership, SOM Rm.M1-109, (816) 235-1780.

Discrimination Grievance Procedures for Students: Discrimination Grievance Procedures for Students can be found here.

English Proficiency Statement

Students who encounter difficulty in their courses because of the English proficiency of their instructors should speak directly with their instructors. If additional assistance is needed, students may contact the UMKC Help Line at 816-235-2222 for assistance.

Grade Appeal Policy

Students are responsible for meeting the standards of academic performance established for each course in which they are enrolled. The establishment of the criteria for grades and the evaluation of student academic performance are the responsibilities of the instructor.

The University grade appeal procedure is available only for the review of allegedly capricious grading and not for review of the instructor’s evaluation of the student’s academic performance. Capricious grading, as that term is used here, comprises any of the following:

The assignment of a grade to a particular student on some basis other than the performance in the course;

The assignment of a grade to a particular student according to more exacting or demanding standards than were applied to other students in the course; (Note: Additional or different grading criteria may be applied to graduate students enrolled for graduate credit in 300- and 400-level courses.)

The assignment of a grade by a substantial departure from the instructor’s previously announced standards.

Students who have concerns about this course should first consult with the specific instructor with whom there is a problem. If the issues are not satisfactorily resolved the student should contact the course director.

In the event a student would like to appeal a course grade they must follow the School of Medicine procedure for grade appeal for graduate courses, which is outlined in the student handbook or can be found at the School of Medicine Graduate Council web page.

Resources

Academic Calendar: Students are encouraged to review important add, drop or withdraw dates: https://www.umkc.edu/calendar/

Campus Safety: Inclement weather, mass notification, and emergency response guide.

Counseling and Health Services Available at UMKC: UMKC students may experience many challenges in their lives while attending college – stress, depression, suicidality, trauma, relationship issues, health concerns, etc. As your professor I care about your success and well-being, and want to make you aware of some helpful resources on campus. The UMKC Counseling Center, located at 4825 Troost in Room 206, offers a wide range of supportive services to students. Appointments can be made by calling 816.235.1635. UMKC Student Health and Wellness, located at 4825 Troost in Room 115, offers a full range of health care and promotion services. Appointments can be scheduled online or by calling 816.235.6133. The MindBody Connection is located in the Atterbury Student Success Center in Room 112 and offers a variety of stress-reduction services.

Disability Support Services: To obtain disability related accommodations and/or auxiliary aids, students with disabilities must contact the Office of Services for Students with Disabilities (OSSD) as soon as possible. To contact OSSD, call (816) 235-5696 or visit their website. Once verified, OSSD will notify the course instructor and outline the accommodation and/or auxiliary aids to be provided. UMKC has a web page with more information about disability services.

Severe Weather Policy: Cancellation of classes will be posted on the front page of the University’s website as well as through the UMKC Alert message system.

Statement of Human Rights: The Board of Curators and UMKC are committed to the policy of equal opportunity, regardless of race, color, religion, sex, sexual orientation, national origin, age, disability and status as a Vietnam era veteran. Commitment to the policy is mentored by the Division of Diversity Equity, but it is the responsibility of the entire university community to provide equal opportunity through relevant practices, initiatives and programs.

Title IX: Under the University of Missouri’s Title IX policy, discrimination, violence and harassment based on sex, gender, and gender identity are subject to the same kinds of accountability and support applied to offenses based on other protected characteristics such as race, color, ethnic or national origin, sexual orientation, religion, age, ancestry, disability, military status, and veteran status. If you or someone you know has been harassed or assaulted, you can find the appropriate resources by visiting UMKC’s Title IX Office webpage or contacting UMKC’s Title IX Coordinator, Mikah K. Thompson (816.235.6910 or thompsonmikah@umkc.edu). Additionally, you can file a complaint using UMKC’s online discrimination complaint form.

While most UMKC employees are required to report any known or suspected violation of Title IX, students may seek confidential guidance from the following campus locations: UMKC Counseling Service Volker Campus 4825 Troost Ave, Suite 206 Kansas City, MO 64110 Phone – (816) 235-1635 UMKC Counseling Service Health Sciences Campus Health Sciences Building 1418 2464 Charlotte Kansas City, MO 64108 Phone – (816) 235-1635 (open Tuesdays, 1-5pm) Student Health and Wellness 4825 Troost Ave., Suite 115 Kansas City, MO 64110 Phone - (816) 235-6133
This document was written on 2020-08-26 and last modifed on `r Sys.Date()`.