---
title: "Where do research ideas come from?"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Elements of a research hypothesis

+ PICO
  + P = patient population
  + I = intervention (or exposure)
  + C = control or comparison group
  + O = outcome
+ PICOTS
  + T = time frame
  + S = setting
  
::: notes

To try to characterize research, especially research that includes a hypothesis, I look for four elements, P, I, C, and O. This comes from evidence-based medicine, the step where you ask an answerable question. In order to do a good job with evidence-based medicine, you first have to pose a question in a way that can be answered by reviewing the literature, reviewing the evidence. Okay, so the experts in evidence based medicine came up with this acronym, PICO. You don't always apply this too literally, but find that it helps.

P is the patient population: who you studied. Are you studying children, or studying the elderly. Are you studying people who present with the neck fracture? Sometimes it is not people. Sometimes, you are you studying the houses that people live in, because you are interested in environmental hazards like lead paint in the home.

I is the intervention. An intervention is when you when you change something. You try to physically intervene to mitigate the problem. You give a drug or offer a therapy. Sometimes I use the word exposure. Exposure is something that your patients endure. It's not something that you provide hoping for a cure. Second hand smoke is an exposure. Non-ionizing radiation is an exposure. Interventions are sometimes bad, but the intention is what matter. An intervention is intended to make things better, while an exposure is something that might make things worse.

C is the control or comparison group. Research hypothesis, almost always, involves some sort of comparison groups. Typically it is a control group. The control group either does not get the intervention, or they get part of the intervention only, or they get an alternate intervention.

There certain cases where you don't have a comparison group. If you are trying to assess the quality of a diagnostic test, it gets a bit harder because everyone gets the diagnostic test. You can try to force this by defining a C, but this is usually not worth the effort.

There's an extension of this acronym, PICOTS. T specifies the time frame and S specifies the setting. These are important differences between a study based in a tertiary care center rather than in a first-line clinic. I sometimes look for the T and the S, but I always look for the first four, P-I-C-O.

:::

## Where do research ideas come from?

Ronan Conroy has an excellent summary.

* Exploring your environment.

* Don't focus prematurely on a single idea.

* Extending the ideas of others.

* Getting a research idea by reading papers.

My theory

* Irritation

::: notes

There's an excellent summary of how to come up with a research idea that I was asked to host on my website. It was collated from various postings on an email discussion group by Ronan Conroy.

I have lost touch with Ronan Conroy, but he and I use to correspond by Internet a lot. He's a really smart guy in Ireland who wrote a very nice summary of where do research ideas come from. He pulled a bunch of ideas from the discussion board that he was on and he wrote it up very nicely. He came to me and asked if I could post his summary on my website. I was happy to do this, because it was so well written.

His outline has four main topics. I don't want to go into too much detail, but the first suggestion is to explore your environment. Look around. Sometimes stuff is sitting right under your nose. Now there are two types of students in this class. There are students who are already deeply involved in clinical responsibilities. They may be a medical resident or fellow, they may actually have the terminal medical degree, and they want to get more involved in research. These students usually are swimming in ideas because there's all this they see every day in the clinic. 

Now I have to say I'm not good at this because I don't do clinical work. I don't see patients. I'm looking from the outside. Sometimes that's a big advantage. I can be more objective about problems, I can look at the problem more abstractly. I can bring in solutions from other disciplines. So it's good to be an outsider to some extent. But if you're like me and your background is more mathematical or more computational, you may have trouble coming up with a good research idea. You don't live in the clinic the way other students do. See if you can talk to someone who has that clinical experience and ask them for help picking a good research topic.

The other thing is to avoid focusing prematurely on a single idea. You need that branch out and not have tunnel vision.

A third approach is to extend the ideas of others. William Shakespeare was a great, great writer, wrote some wonderful plays, but he stole most of these plays from someone else. He just wrote them so much better than the original sources that that's why we remember his name today and not any of those other people.

Extending the idea of others is not plagiarism. It's not stealing. It's part of research. So, for example, there may be a a fair amount known already about how to get people to lose weight when they are physically handicapped and do not have the ability to exercise. Even so, there is always a way to improve one the currently best available interventions.

If we are talking about treatment of cancer, there are always ways we can improve the treatments. For example, you might work to reduce the side effects of some these very harsh drugs. 

If you are a beginning resarchers, the last thing you want to try to do is come up with something that's totally de novo, something that's brand-new, something that no one else has ever thought of. Few of us, and I put myself in this category, are so smart that they can develop something brand-new is never been thought of before.

The last suggesiton is closely related. Read other people's research papers. These papers have a literature review, a methods section, a  results section, and a discussion section. Look at that discussion and look at where they say "options for further research." These people are giving you free advice.

Okay, now my theory about research is a lot simpler why people do research. It's the irritation principal. They see something's wrong and it just bothers them. There are two types of wrong. There's I'm doing something right now that I know I could be doing better okay. There is also I'm doing it right, but no one else is. Either way, there's a sense of irritation. It's that they have an itch that they just have to scratch. There is something that needs to be fixed and I won't feel right until I try to fix it. That's where I think for a lot of research ideas come from. 

All these ideas are all good, but let me emphasize the importance of reading. Almost every research paper includes suggestions for further research in their discussion section. This is free advice from researchers who have proved that they can get their work published.

:::

## Uses of clinical research

* Practical application.

* Theory development.

* Development of research tools.

* Professional development.

::: notes

Why do we do clinical research? Let's let's be honest about this is several reasons. It's not just the practical application--learning about something that can improve the care you provide to your patients. 
Sometimes research is done for theory development--understanding why and how diseases progress. 

You can also conduct research to develop new tools to improve the research process (this is an area I am very interested in). 

You can also conduct research for your own professional development. Nothing makes you a better consumer of other people's research than doing a bit of research yourself.

It's important to understand your motivations for doing research, because different motivations result in different priorities. In particular, the pedagogical benefits of conducting a research study will often drive a thesis committee to encourage approaches that broaden a student's understanding of the research process, even though a different approach might be better.

Don't get me wrong. Most of the time you can improve your knowledge and benefit your patients at the same time. 

:::
