---
title: "Comments for MEDB 5501, Week 9"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Review confidence interval for a single mean, 1 of 3

If n \< 30, we have 1-$\alpha$ level of confidence that the population mean lies between

-   $\bar{X}-t(\alpha/2; n-1)se(\bar{X})$ and
-   $\bar{X}+t(\alpha/2; n-1)se(\bar{X})$

## Review confidence interval for a single mean, 2 of 3

If n \> 30, we have 1-$\alpha$ level of confidence that the population mean lies between

-   $\bar{X}-Z(\alpha/2)se(\bar{X})$ and
-   $\bar{X}+Z(\alpha/2)se(\bar{X})$

## Review confidence interval for a single mean, 3 of 3

Very rough rule of thumb (do not use in publications, grants. Do not use on your homework, unless specifically requested).

-   $\bar{X} - 2 \times se(\bar{X})$ and
-   $\bar{X} + 2 \times se(\bar{X})$

represent an approximate 95% confidence interval for the population mean.

## Example, 1 of 3

-   In a sample of 98 women who smoked during pregnancy, the average BMI of these women prior to pregnancy was 21.6 with a standard deviation of 2.3. You calculate a standard error of the mean equal to 0.23.
-   Link information is on the Canvas site, or you can search for PMID 37822980 on PubMed

## Example, 2 of 3

-   Construct and interpret an approximate 95% confidence interval using the simple approximation.
    -   $21.6 \pm 2 \times 0.23$
    -   $21.6 \pm 0.46$
    -   $(21.14, 22.06)$

## Example, 3 of 3

-   Interpretation
    -   We are 95% confident that the average weight of all women in Great Britain who smoked during their pregnancy is somewhere between 21.14 and 22.06 kilograms per meter squared.

## Confidence interval for a single proportion, 1 of 2

Let p represent a proportion computed from a sample. You wish to create a confidence interval for $\pi$, the proportion in the entire population.

-   $se(p)=\sqrt{\frac{p(1-p)}{n}}$

## Confidence interval for a single proportion, 2 of 2

-   $p-Z(\alpha/2)se(p)$ and
-   $p+Z(\alpha/2)se(p)$

is an approximate $1-\alpha$ confidence interval for $\pi$.

-   Note that this confidence interval uses z rather than t, regardless of the sample size.

## Example, 1 of 3

In the same study, 27 of the 102 women (26.5%) were primiparous. Construct an approximate 95% confidence interval for the proportion of primiparous women in the population.

The standard error is

-   $se(p)=\sqrt{\frac{0.265 \times 0.735}{102}}=0.0436985 \approx 0.044$

## Example, 2 of 3

The approximate confidence interval is

-   $0.265 \pm 2 \times 0.044$
-   $0.265 \pm 0.088$
-   $0.177$ to $0.353$

## Example, 3 of 3

Interpretation:

-   We are 95% confident that the proportion of primiparous women among all women in Great Britain who smoked during pregnancy is somewhere betweeen 18% and 35%.
